import CrownFloatingExtendedArtFix from './images/crown/floating/extendedArtFix.png';
import CrownMask from './images/crown/maskCrown.png';
import CrownArtefact from './images/crown/a.png';
import CrownArtefactLowRes from './images/crown/aThumb.png';
import CrownArtefactFloating from './images/crown/floating/a.png';
import CrownColorlessFloating from './images/crown/floating/a.png';
import CrownArtefactFloatingLowRes from './images/crown/floating/aThumb.png';
import CrownColorlessFloatingLowRes from './images/crown/floating/aThumb.png';
import CrownArtefactNickname from './images/crown/nickname/a.png';
import CrownColorlessNickname from './images/crown/nickname/a.png';
import CrownArtefactNicknameLowRes from './images/crown/nickname/aThumb.png';
import CrownColorlessNicknameLowRes from './images/crown/nickname/aThumb.png';
import CrownWhite from './images/crown/w.png';
import CrownWhiteLowRes from './images/crown/wThumb.png';
import CrownWhiteFloating from './images/crown/floating/w.png';
import CrownWhiteFloatingLowRes from './images/crown/floating/wThumb.png';
import CrownWhiteNickname from './images/crown/nickname/w.png';
import CrownWhiteNicknameLowRes from './images/crown/nickname/wThumb.png';
import CrownBlue from './images/crown/u.png';
import CrownBlueLowRes from './images/crown/uThumb.png';
import CrownBlueFloating from './images/crown/floating/u.png';
import CrownBlueFloatingLowRes from './images/crown/floating/uThumb.png';
import CrownBlueNickname from './images/crown/nickname/u.png';
import CrownBlueNicknameLowRes from './images/crown/nickname/uThumb.png';
import CrownBlack from './images/crown/b.png';
import CrownBlackLowRes from './images/crown/bThumb.png';
import CrownBlackFloating from './images/crown/floating/b.png';
import CrownBlackFloatingLowRes from './images/crown/floating/bThumb.png';
import CrownBlackNickname from './images/crown/nickname/b.png';
import CrownBlackNicknameLowRes from './images/crown/nickname/bThumb.png';
import CrownRed from './images/crown/r.png';
import CrownRedLowRes from './images/crown/rThumb.png';
import CrownRedFloating from './images/crown/floating/r.png';
import CrownRedFloatingLowRes from './images/crown/floating/rThumb.png';
import CrownRedNickname from './images/crown/nickname/r.png';
import CrownRedNicknameLowRes from './images/crown/nickname/rThumb.png';
import CrownGreen from './images/crown/g.png';
import CrownGreenLowRes from './images/crown/gThumb.png';
import CrownGreenFloating from './images/crown/floating/g.png';
import CrownGreenFloatingLowRes from './images/crown/floating/gThumb.png';
import CrownGreenNickname from './images/crown/nickname/g.png';
import CrownGreenNicknameLowRes from './images/crown/nickname/gThumb.png';
import CrownGold from './images/crown/m.png';
import CrownGoldLowRes from './images/crown/mThumb.png';
import CrownGoldFloating from './images/crown/floating/m.png';
import CrownGoldFloatingLowRes from './images/crown/floating/mThumb.png';
import CrownGoldNickname from './images/crown/nickname/m.png';
import CrownGoldNicknameLowRes from './images/crown/nickname/mThumb.png';
import CrownLand from './images/crown/l.png';
import CrownLandLowRes from './images/crown/lThumb.png';
import CrownLandFloating from './images/crown/floating/l.png';
import CrownLandFloatingLowRes from './images/crown/floating/lThumb.png';
import CrownLandNickname from './images/crown/nickname/l.png';
import CrownLandNicknameLowRes from './images/crown/nickname/lThumb.png';
import CrownColorless from './images/crown/c.png';
import CrownColorlessLowRes from './images/crown/cThumb.png';
// Two-color crown combos (WUBRG wheel order), for the base, floating (full-art)
// and nickname crown styles. Generated by scripts/generate-parts.cjs.
import CrownWu from './images/crown/wu.png';
import CrownWuLowRes from './images/crown/wuThumb.png';
import CrownWuFloating from './images/crown/floating/wu.png';
import CrownWuFloatingLowRes from './images/crown/floating/wuThumb.png';
import CrownWuNickname from './images/crown/nickname/wu.png';
import CrownWuNicknameLowRes from './images/crown/nickname/wuThumb.png';
import CrownUb from './images/crown/ub.png';
import CrownUbLowRes from './images/crown/ubThumb.png';
import CrownUbFloating from './images/crown/floating/ub.png';
import CrownUbFloatingLowRes from './images/crown/floating/ubThumb.png';
import CrownUbNickname from './images/crown/nickname/ub.png';
import CrownUbNicknameLowRes from './images/crown/nickname/ubThumb.png';
import CrownBr from './images/crown/br.png';
import CrownBrLowRes from './images/crown/brThumb.png';
import CrownBrFloating from './images/crown/floating/br.png';
import CrownBrFloatingLowRes from './images/crown/floating/brThumb.png';
import CrownBrNickname from './images/crown/nickname/br.png';
import CrownBrNicknameLowRes from './images/crown/nickname/brThumb.png';
import CrownRg from './images/crown/rg.png';
import CrownRgLowRes from './images/crown/rgThumb.png';
import CrownRgFloating from './images/crown/floating/rg.png';
import CrownRgFloatingLowRes from './images/crown/floating/rgThumb.png';
import CrownRgNickname from './images/crown/nickname/rg.png';
import CrownRgNicknameLowRes from './images/crown/nickname/rgThumb.png';
import CrownGw from './images/crown/gw.png';
import CrownGwLowRes from './images/crown/gwThumb.png';
import CrownGwFloating from './images/crown/floating/gw.png';
import CrownGwFloatingLowRes from './images/crown/floating/gwThumb.png';
import CrownGwNickname from './images/crown/nickname/gw.png';
import CrownGwNicknameLowRes from './images/crown/nickname/gwThumb.png';
import CrownWb from './images/crown/wb.png';
import CrownWbLowRes from './images/crown/wbThumb.png';
import CrownWbFloating from './images/crown/floating/wb.png';
import CrownWbFloatingLowRes from './images/crown/floating/wbThumb.png';
import CrownWbNickname from './images/crown/nickname/wb.png';
import CrownWbNicknameLowRes from './images/crown/nickname/wbThumb.png';
import CrownUr from './images/crown/ur.png';
import CrownUrLowRes from './images/crown/urThumb.png';
import CrownUrFloating from './images/crown/floating/ur.png';
import CrownUrFloatingLowRes from './images/crown/floating/urThumb.png';
import CrownUrNickname from './images/crown/nickname/ur.png';
import CrownUrNicknameLowRes from './images/crown/nickname/urThumb.png';
import CrownBg from './images/crown/bg.png';
import CrownBgLowRes from './images/crown/bgThumb.png';
import CrownBgFloating from './images/crown/floating/bg.png';
import CrownBgFloatingLowRes from './images/crown/floating/bgThumb.png';
import CrownBgNickname from './images/crown/nickname/bg.png';
import CrownBgNicknameLowRes from './images/crown/nickname/bgThumb.png';
import CrownRw from './images/crown/rw.png';
import CrownRwLowRes from './images/crown/rwThumb.png';
import CrownRwFloating from './images/crown/floating/rw.png';
import CrownRwFloatingLowRes from './images/crown/floating/rwThumb.png';
import CrownRwNickname from './images/crown/nickname/rw.png';
import CrownRwNicknameLowRes from './images/crown/nickname/rwThumb.png';
import CrownGu from './images/crown/gu.png';
import CrownGuLowRes from './images/crown/guThumb.png';
import CrownGuFloating from './images/crown/floating/gu.png';
import CrownGuFloatingLowRes from './images/crown/floating/guThumb.png';
import CrownGuNickname from './images/crown/nickname/gu.png';
import CrownGuNicknameLowRes from './images/crown/nickname/guThumb.png';
import InnerCrownArtefact from './images/crown/m15InnerCrownANyx.png';
import InnerCrownWhite from './images/crown/m15InnerCrownWNyx.png';
import InnerCrownBlue from './images/crown/m15InnerCrownUNyx.png';
import InnerCrownBlack from './images/crown/m15InnerCrownBNyx.png';
import InnerCrownRed from './images/crown/m15InnerCrownRNyx.png';
import InnerCrownGreen from './images/crown/m15InnerCrownGNyx.png';
import InnerCrownGold from './images/crown/m15InnerCrownMNyx.png';

import Black from './images/black.png';

import VehicleMainframe from './images/mainframes/m15/v.png';
import ArtefactMainframe from './images/mainframes/m15/a.png';
import ArtefactNyxMainframe from './images/mainframes/m15/nyx/a.png';
import ColorlessNyxMainframe from './images/mainframes/m15/nyx/a.png';
import WhiteMainframe from './images/mainframes/m15/w.png';
import WhiteNyxMainframe from './images/mainframes/m15/nyx/w.png';
import BlueMainframe from './images/mainframes/m15/u.png';
import BlueNyxMainframe from './images/mainframes/m15/nyx/u.png';
import BlackMainframe from './images/mainframes/m15/b.png';
import BlackNyxMainframe from './images/mainframes/m15/nyx/b.png';
import RedMainframe from './images/mainframes/m15/r.png';
import RedNyxMainframe from './images/mainframes/m15/nyx/r.png';
import GreenMainframe from './images/mainframes/m15/g.png';
import GreenNyxMainframe from './images/mainframes/m15/nyx/g.png';
import GoldMainframe from './images/mainframes/m15/m.png';
import GoldNyxMainframe from './images/mainframes/m15/nyx/m.png';
import ColorlessMainframe from './images/mainframes/m15/c.png';

import BorderlessFrameA from './images/mainframes/borderless/m15GenericShowcaseFrameA.png';
import BorderlessFrameC from './images/mainframes/borderless/m15GenericShowcaseFrameC.png';
import BorderlessFrameL from './images/mainframes/borderless/m15GenericShowcaseFrameL.png';
import BorderlessFrameW from './images/mainframes/borderless/m15GenericShowcaseFrameW.png';
import BorderlessFrameU from './images/mainframes/borderless/m15GenericShowcaseFrameU.png';
import BorderlessFrameB from './images/mainframes/borderless/m15GenericShowcaseFrameB.png';
import BorderlessFrameR from './images/mainframes/borderless/m15GenericShowcaseFrameR.png';
import BorderlessFrameG from './images/mainframes/borderless/m15GenericShowcaseFrameG.png';
import BorderlessFrameM from './images/mainframes/borderless/m15GenericShowcaseFrameM.png';
import BorderlessNicknameFrameA from './images/mainframes/borderless/nickname/m15NicknameFrameA.png';
import BorderlessNicknameFrameC from './images/mainframes/borderless/nickname/m15NicknameFrameA.png';
import BorderlessNicknameFrameL from './images/mainframes/borderless/nickname/m15NicknameFrameL.png';
import BorderlessNicknameFrameW from './images/mainframes/borderless/nickname/m15NicknameFrameW.png';
import BorderlessNicknameFrameU from './images/mainframes/borderless/nickname/m15NicknameFrameU.png';
import BorderlessNicknameFrameB from './images/mainframes/borderless/nickname/m15NicknameFrameB.png';
import BorderlessNicknameFrameR from './images/mainframes/borderless/nickname/m15NicknameFrameR.png';
import BorderlessNicknameFrameG from './images/mainframes/borderless/nickname/m15NicknameFrameG.png';
import BorderlessNicknameFrameM from './images/mainframes/borderless/nickname/m15NicknameFrameM.png';

import ExtendedFrameA from './images/mainframes/extended/a.png';
import ExtendedFrameANyx from './images/mainframes/extended/nyx/a.png';
import ExtendedFrameV from './images/mainframes/extended/v.png';
import ExtendedFrameC from './images/mainframes/extended/c.png';
import ExtendedFrameL from './images/mainframes/extended/l.png';
import ExtendedFrameWNyx from './images/mainframes/extended/nyx/w.png';
import ExtendedFrameW from './images/mainframes/extended/w.png';
import ExtendedFrameWL from './images/mainframes/extended/lw.png';
import ExtendedFrameU from './images/mainframes/extended/u.png';
import ExtendedFrameUNyx from './images/mainframes/extended/nyx/u.png';
import ExtendedFrameUL from './images/mainframes/extended/lu.png';
import ExtendedFrameB from './images/mainframes/extended/b.png';
import ExtendedFrameBNyx from './images/mainframes/extended/nyx/b.png';
import ExtendedFrameBL from './images/mainframes/extended/lb.png';
import ExtendedFrameR from './images/mainframes/extended/r.png';
import ExtendedFrameRNyx from './images/mainframes/extended/nyx/r.png';
import ExtendedFrameRL from './images/mainframes/extended/lr.png';
import ExtendedFrameG from './images/mainframes/extended/g.png';
import ExtendedFrameGNyx from './images/mainframes/extended/nyx/g.png';
import ExtendedFrameGL from './images/mainframes/extended/lg.png';
import ExtendedFrameM from './images/mainframes/extended/m.png';
import ExtendedFrameMNyx from './images/mainframes/extended/nyx/m.png';
import ExtendedFrameML from './images/mainframes/extended/lm.png';

import TokenArtefactMainframe from './images/mainframes/token/Art.png';
import TokenColorlessMainframe from './images/mainframes/token/C.png';
import TokenWhiteMainframe from './images/mainframes/token/W.png';
import TokenBlueMainframe from './images/mainframes/token/U.png';
import TokenBlackMainframe from './images/mainframes/token/B.png';
import TokenRedMainframe from './images/mainframes/token/R.png';
import TokenGreenMainframe from './images/mainframes/token/G.png';
import TokenGoldMainframe from './images/mainframes/token/Gld.png';

import InvocationWhiteMainframe from './images/mainframes/invocation/W.png';
import InvocationBlueMainframe from './images/mainframes/invocation/U.png';
import InvocationBlackMainframe from './images/mainframes/invocation/B.png';
import InvocationRedMainframe from './images/mainframes/invocation/R.png';
import InvocationGreenMainframe from './images/mainframes/invocation/G.png';
import InvocationGoldMainframe from './images/mainframes/invocation/Gld.png';

import InventionArtefactMainframe from './images/mainframes/invention/a.png';
import InventionColorlessMainframe from './images/mainframes/invention/l.png';
import InventionWhiteMainframe from './images/mainframes/invention/w.png';
import InventionBlueMainframe from './images/mainframes/invention/u.png';
import InventionBlackMainframe from './images/mainframes/invention/b.png';
import InventionRedMainframe from './images/mainframes/invention/r.png';
import InventionGreenMainframe from './images/mainframes/invention/g.png';
import InventionGoldMainframe from './images/mainframes/invention/m.png';

import LowResWhiteMainframe from './images/mainframes/m15/wThumb.png';
import LowResBlueMainframe from './images/mainframes/m15/uThumb.png';
import LowResBlackMainframe from './images/mainframes/m15/bThumb.png';
import LowResRedMainframe from './images/mainframes/m15/rThumb.png';
import LowResGreenMainframe from './images/mainframes/m15/gThumb.png';
import LowResGoldMainframe from './images/mainframes/m15/mThumb.png';
import LowResColorlessMainframe from './images/mainframes/m15/cThumb.png';
import LowResArtefactMainframe from './images/mainframes/m15/aThumb.png';
import LowResVehicleMainframe from './images/mainframes/m15/vThumb.png';

import LowResWhiteMainframeNyx from './images/mainframes/m15/nyx/wThumb.png';
import LowResBlueMainframeNyx from './images/mainframes/m15/nyx/uThumb.png';
import LowResBlackMainframeNyx from './images/mainframes/m15/nyx/bThumb.png';
import LowResRedMainframeNyx from './images/mainframes/m15/nyx/rThumb.png';
import LowResGreenMainframeNyx from './images/mainframes/m15/nyx/gThumb.png';
import LowResGoldMainframeNyx from './images/mainframes/m15/nyx/mThumb.png';
import LowResColorlessMainframeNyx from './images/mainframes/m15/nyx/aThumb.png';
import LowResArtefactMainframeNyx from './images/mainframes/m15/nyx/aThumb.png';

import UnstableBasicLandWhiteMainframe from './images/mainframes/lands/unstable/W.png';
import UnstableBasicLandBlueMainframe from './images/mainframes/lands/unstable/U.png';
import UnstableBasicLandBlackMainframe from './images/mainframes/lands/unstable/B.png';
import UnstableBasicLandRedMainframe from './images/mainframes/lands/unstable/R.png';
import UnstableBasicLandGreenMainframe from './images/mainframes/lands/unstable/G.png';
import UnstableBasicLandGoldMainframe from './images/mainframes/lands/unstable/Gld.png';

import FullArtBasicLandWhiteMainframe from './images/mainframes/lands/fullArt/W.png';
import FullArtBasicLandBlueMainframe from './images/mainframes/lands/fullArt/U.png';
import FullArtBasicLandBlackMainframe from './images/mainframes/lands/fullArt/B.png';
import FullArtBasicLandRedMainframe from './images/mainframes/lands/fullArt/R.png';
import FullArtBasicLandGreenMainframe from './images/mainframes/lands/fullArt/G.png';
import FullArtBasicLandGoldMainframe from './images/mainframes/lands/fullArt/A.png';

import LandWhiteMainframe from './images/mainframes/lands/lw.png';
import LandBlueMainframe from './images/mainframes/lands/lu.png';
import LandBlackMainframe from './images/mainframes/lands/lb.png';
import LandRedMainframe from './images/mainframes/lands/lr.png';
import LandGreenMainframe from './images/mainframes/lands/lg.png';
import LandGoldMainframe from './images/mainframes/lands/lm.png';
import LandColorlessMainframe from './images/mainframes/lands/l.png';
import LandWhiteMainframeLowRes from './images/mainframes/lands/lwThumb.png';
import LandBlueMainframeLowRes from './images/mainframes/lands/luThumb.png';
import LandBlackMainframeLowRes from './images/mainframes/lands/lbThumb.png';
import LandRedMainframeLowRes from './images/mainframes/lands/lrThumb.png';
import LandGreenMainframeLowRes from './images/mainframes/lands/lgThumb.png';
import LandGoldMainframeLowRes from './images/mainframes/lands/lmThumb.png';
import LandColorlessMainframeLowRes from './images/mainframes/lands/lThumb.png';

import WhitePinline from './images/parts/pinline/w.png';
import BluePinline from './images/parts/pinline/u.png';
import BlackPinline from './images/parts/pinline/b.png';
import RedPinline from './images/parts/pinline/r.png';
import GreenPinline from './images/parts/pinline/g.png';
import GoldPinline from './images/parts/pinline/m.png';
import WhiteBluePinline from './images/parts/pinline/wu.png';
import BlueBlackPinline from './images/parts/pinline/ub.png';
import BlackRedPinline from './images/parts/pinline/br.png';
import RedGreenPinline from './images/parts/pinline/rg.png';
import GreenWhitePinline from './images/parts/pinline/gw.png';
import WhiteBlackPinline from './images/parts/pinline/wb.png';
import BlueRedPinline from './images/parts/pinline/ur.png';
import BlackGreenPinline from './images/parts/pinline/bg.png';
import RedWhitePinline from './images/parts/pinline/rw.png';
import GreenBluePinline from './images/parts/pinline/gu.png';

import ExtendedWhiteBluePinline from './images/parts/pinline/extended/wu.png';
import ExtendedBlueBlackPinline from './images/parts/pinline/extended/ub.png';
import ExtendedBlackRedPinline from './images/parts/pinline/extended/br.png';
import ExtendedRedGreenPinline from './images/parts/pinline/extended/rg.png';
import ExtendedGreenWhitePinline from './images/parts/pinline/extended/gw.png';
import ExtendedWhiteBlackPinline from './images/parts/pinline/extended/wb.png';
import ExtendedBlueRedPinline from './images/parts/pinline/extended/ur.png';
import ExtendedBlackGreenPinline from './images/parts/pinline/extended/bg.png';
import ExtendedRedWhitePinline from './images/parts/pinline/extended/rw.png';
import ExtendedGreenBluePinline from './images/parts/pinline/extended/gu.png';

import BorderlessWhiteBluePinline from './images/parts/pinline/borderless/wu.png';
import BorderlessBlueBlackPinline from './images/parts/pinline/borderless/ub.png';
import BorderlessBlackRedPinline from './images/parts/pinline/borderless/br.png';
import BorderlessRedGreenPinline from './images/parts/pinline/borderless/rg.png';
import BorderlessGreenWhitePinline from './images/parts/pinline/borderless/gw.png';
import BorderlessWhiteBlackPinline from './images/parts/pinline/borderless/wb.png';
import BorderlessBlueRedPinline from './images/parts/pinline/borderless/ur.png';
import BorderlessBlackGreenPinline from './images/parts/pinline/borderless/bg.png';
import BorderlessRedWhitePinline from './images/parts/pinline/borderless/rw.png';
import BorderlessGreenBluePinline from './images/parts/pinline/borderless/gu.png';

import WhiteTitle from './images/parts/title/w.png';
import BlueTitle from './images/parts/title/u.png';
import BlackTitle from './images/parts/title/b.png';
import RedTitle from './images/parts/title/r.png';
import GreenTitle from './images/parts/title/g.png';
import GoldTitle from './images/parts/title/m.png';
import WhiteBlueTitle from './images/parts/title/wu.png';
import BlueBlackTitle from './images/parts/title/ub.png';
import BlackRedTitle from './images/parts/title/br.png';
import RedGreenTitle from './images/parts/title/rg.png';
import GreenWhiteTitle from './images/parts/title/gw.png';
import WhiteBlackTitle from './images/parts/title/wb.png';
import BlueRedTitle from './images/parts/title/ur.png';
import BlackGreenTitle from './images/parts/title/bg.png';
import RedWhiteTitle from './images/parts/title/rw.png';
import GreenBlueTitle from './images/parts/title/gu.png';

import WhiteType from './images/parts/type/w.png';
import BlueType from './images/parts/type/u.png';
import BlackType from './images/parts/type/b.png';
import RedType from './images/parts/type/r.png';
import GreenType from './images/parts/type/g.png';
import GoldType from './images/parts/type/m.png';
import WhiteBlueType from './images/parts/type/wu.png';
import BlueBlackType from './images/parts/type/ub.png';
import BlackRedType from './images/parts/type/br.png';
import RedGreenType from './images/parts/type/rg.png';
import GreenWhiteType from './images/parts/type/gw.png';
import WhiteBlackType from './images/parts/type/wb.png';
import BlueRedType from './images/parts/type/ur.png';
import BlackGreenType from './images/parts/type/bg.png';
import RedWhiteType from './images/parts/type/rw.png';
import GreenBlueType from './images/parts/type/gu.png';

import LandTitle from './images/parts/title/l.png';
import LandType from './images/parts/type/l.png';

import WhiteRules from './images/parts/rules/w.png';
import BlueRules from './images/parts/rules/u.png';
import BlackRules from './images/parts/rules/b.png';
import RedRules from './images/parts/rules/r.png';
import GreenRules from './images/parts/rules/g.png';
import GoldRules from './images/parts/rules/m.png';
import WhiteBlueRules from './images/parts/rules/wu.png';
import BlueBlackRules from './images/parts/rules/ub.png';
import BlackRedRules from './images/parts/rules/br.png';
import RedGreenRules from './images/parts/rules/rg.png';
import GreenWhiteRules from './images/parts/rules/gw.png';
import WhiteBlackRules from './images/parts/rules/wb.png';
import BlueRedRules from './images/parts/rules/ur.png';
import BlackGreenRules from './images/parts/rules/bg.png';
import RedWhiteRules from './images/parts/rules/rw.png';
import GreenBlueRules from './images/parts/rules/gu.png';

import LandOverlay from './images/overlay/C-overlay.png';
import InvocationPt from './images/pt/invocation/A.png';
import InventionPt from './images/pt/invention/inventionPT.png';
import PtA from './images/pt/regular/m15PTA.png';
import PtW from './images/pt/regular/m15PTW.png';
import PtU from './images/pt/regular/m15PTU.png';
import PtB from './images/pt/regular/m15PTB.png';
import PtR from './images/pt/regular/m15PTR.png';
import PtG from './images/pt/regular/m15PTM.png';
import PtM from './images/pt/regular/m15PTM.png';
import PtC from './images/pt/regular/m15PTC.png';
import PtANickname from './images/pt/nickname/m15NicknamePTA.png';
import PtWNickname from './images/pt/nickname/m15NicknamePTW.png';
import PtUNickname from './images/pt/nickname/m15NicknamePTU.png';
import PtBNickname from './images/pt/nickname/m15NicknamePTB.png';
import PtRNickname from './images/pt/nickname/m15NicknamePTR.png';
import PtGNickname from './images/pt/nickname/m15NicknamePTM.png';
import PtMNickname from './images/pt/nickname/m15NicknamePTM.png';
import PtCNickname from './images/pt/nickname/m15NicknamePTC.png';
import PtABorderless from './images/pt/borderless/a.png';
import PtWBorderless from './images/pt/borderless/w.png';
import PtUBorderless from './images/pt/borderless/u.png';
import PtBBorderless from './images/pt/borderless/b.png';
import PtRBorderless from './images/pt/borderless/r.png';
import PtGBorderless from './images/pt/borderless/g.png';
import PtCBorderless from './images/pt/borderless/c.png';
import PtMBorderless from './images/pt/borderless/m.png';
import PtVBorderless from './images/pt/borderless/v.png';
import PtLBorderless from './images/pt/borderless/l.png';

import SymbolLandWhite from './images/symbols/land/W.png';
import SymbolLandBlue from './images/symbols/land/U.png';
import SymbolLandBlack from './images/symbols/land/B.png';
import SymbolLandRed from './images/symbols/land/R.png';
import SymbolLandGreen from './images/symbols/land/G.png';
import SymbolLandColorless from './images/symbols/land/C.png';

import MythicRareIcon from './images/rarity/mythic.png';
import RareIcon from './images/rarity/rare.png';
import UncommonIcon from './images/rarity/uncommon.png';
import CommonIcon from './images/rarity/common.png';

import {
  BasicLandArtStyles,
  BasicLandType,
  CardArtStyles,
  ColorType,
  RarityType,
} from '../../interfaces/enums';

import PlaneswalkerWhiteMainframe from './images/mainframes/planeswalker/W.png';
import PlaneswalkerWhiteMainframe2 from './images/mainframes/planeswalker/W2.png';
import PlaneswalkerWhiteMainframe4 from './images/mainframes/planeswalker/W4.png';
import PlaneswalkerBlueMainframe from './images/mainframes/planeswalker/U.png';
import PlaneswalkerBlueMainframe2 from './images/mainframes/planeswalker/U2.png';
import PlaneswalkerBlueMainframe4 from './images/mainframes/planeswalker/U4.png';
import PlaneswalkerBlackMainframe from './images/mainframes/planeswalker/B.png';
import PlaneswalkerBlackMainframe2 from './images/mainframes/planeswalker/B2.png';
import PlaneswalkerBlackMainframe4 from './images/mainframes/planeswalker/B4.png';
import PlaneswalkerRedMainframe from './images/mainframes/planeswalker/R.png';
import PlaneswalkerRedMainframe2 from './images/mainframes/planeswalker/R2.png';
import PlaneswalkerRedMainframe4 from './images/mainframes/planeswalker/R4.png';
import PlaneswalkerGreenMainframe from './images/mainframes/planeswalker/G.png';
import PlaneswalkerGreenMainframe2 from './images/mainframes/planeswalker/G2.png';
import PlaneswalkerGreenMainframe4 from './images/mainframes/planeswalker/G4.png';
import PlaneswalkerColorlessMainframe from './images/mainframes/planeswalker/Art.png';
import PlaneswalkerColorlessMainframe2 from './images/mainframes/planeswalker/Art2.png';
import PlaneswalkerColorlessMainframe4 from './images/mainframes/planeswalker/Art4.png';
import PlaneswalkerGoldMainframe from './images/mainframes/planeswalker/Gld.png';
import PlaneswalkerGoldMainframe2 from './images/mainframes/planeswalker/Gld2.png';
import PlaneswalkerGoldMainframe4 from './images/mainframes/planeswalker/Gld4.png';

import PlaneswalkerPt from './images/pt/planeswalker/LoyaltyBegin.png';

import LoyaltyUp from './images/symbols/loyalty/LoyaltyUp.png';
import LoyaltyDown from './images/symbols/loyalty/LoyaltyDown.png';
import LoyaltyZero from './images/symbols/loyalty/LoyaltyZero.png';

import NicknameTitleA from './images/nickname/m15NicknameTitleA.png';
import NicknameTitleW from './images/nickname/m15NicknameTitleW.png';
import NicknameTitleU from './images/nickname/m15NicknameTitleU.png';
import NicknameTitleB from './images/nickname/m15NicknameTitleB.png';
import NicknameTitleR from './images/nickname/m15NicknameTitleR.png';
import NicknameTitleG from './images/nickname/m15NicknameTitleG.png';
import NicknameTitleM from './images/nickname/m15NicknameTitleM.png';
import NicknameTitleL from './images/nickname/m15NicknameTitleL.png';
import NicknameTitleWhiteBlue from './images/nickname/m15NicknameTitleWU.png';
import NicknameTitleBlueBlack from './images/nickname/m15NicknameTitleUB.png';
import NicknameTitleBlackRed from './images/nickname/m15NicknameTitleBR.png';
import NicknameTitleRedGreen from './images/nickname/m15NicknameTitleRG.png';
import NicknameTitleGreenWhite from './images/nickname/m15NicknameTitleGW.png';
import NicknameTitleWhiteBlack from './images/nickname/m15NicknameTitleWB.png';
import NicknameTitleBlueRed from './images/nickname/m15NicknameTitleUR.png';
import NicknameTitleBlackGreen from './images/nickname/m15NicknameTitleBG.png';
import NicknameTitleRedWhite from './images/nickname/m15NicknameTitleRW.png';
import NicknameTitleGreenBlue from './images/nickname/m15NicknameTitleGU.png';

export interface ImageResData {
  highRes: string;
  lowRes?: string;
}

// export const getFallbackCover = () => NoCover;
export const getFallbackCover = () => 'https://picsum.photos/700/600';

export const getPt = (
  color: ColorType,
  isArtefact = false,
  isVehicle = false,
  isNickname = false,
  isBorderless = false,
  isLand = false,
) => {
  if (isLand) {
    return PtLBorderless;
  }
  if (isArtefact) {
    if (color === ColorType.Gold) {
      if (isBorderless) {
        return isVehicle ? PtVBorderless : PtMBorderless;
      }
      return isNickname ? PtMNickname : PtM;
    }
    if (isBorderless) {
      return isVehicle ? PtVBorderless : PtABorderless;
    }
    return isNickname ? PtANickname : PtA;
  }

  switch (color) {
    case ColorType.White:
      if (isBorderless) {
        return PtWBorderless;
      }
      return isNickname ? PtWNickname : PtW;
    case ColorType.Blue:
      if (isBorderless) {
        return PtUBorderless;
      }
      return isNickname ? PtUNickname : PtU;
    case ColorType.Black:
      if (isBorderless) {
        return PtBBorderless;
      }
      return isNickname ? PtBNickname : PtB;
    case ColorType.Red:
      if (isBorderless) {
        return PtRBorderless;
      }
      return isNickname ? PtRNickname : PtR;
    case ColorType.Green:
      if (isBorderless) {
        return PtGBorderless;
      }
      return isNickname ? PtGNickname : PtG;
    case ColorType.Gold:
      if (isBorderless) {
        return PtMBorderless;
      }
      return isNickname ? PtMNickname : PtM;
    default:
      if (isBorderless) {
        return PtCBorderless;
      }
      return isNickname ? PtCNickname : PtC;
  }
};

// Two-color nickname title plates, keyed by the combo variant.
const NICKNAME_TITLE_COMBOS: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: NicknameTitleWhiteBlue,
  ub: NicknameTitleBlueBlack,
  br: NicknameTitleBlackRed,
  rg: NicknameTitleRedGreen,
  gw: NicknameTitleGreenWhite,
  wb: NicknameTitleWhiteBlack,
  ur: NicknameTitleBlueRed,
  bg: NicknameTitleBlackGreen,
  rw: NicknameTitleRedWhite,
  gu: NicknameTitleGreenBlue,
};

// On two-color cards the blended combo plate replaces the regular gold ('m')
// plate. Pass the card's colors (card-text identity for lands).
export const getNicknameTitle = (
  color: ColorType,
  isArtefact = false,
  isLand = false,
  colors?: ColorType[],
) => {
  if (isLand && color === ColorType.Colorless) {
    return NicknameTitleL;
  }
  // Two-color cards (including two-color artifacts) use the blended combo plate
  // rather than the gold or artefact plate.
  if (colors && colors.length === 2) {
    return NICKNAME_TITLE_COMBOS[getTwoColorVariant(colors)];
  }
  if (isArtefact) {
    return NicknameTitleA;
  }

  switch (color) {
    case ColorType.White:
      return NicknameTitleW;
    case ColorType.Blue:
      return NicknameTitleU;
    case ColorType.Black:
      return NicknameTitleB;
    case ColorType.Red:
      return NicknameTitleR;
    case ColorType.Green:
      return NicknameTitleG;
    case ColorType.Gold:
      return NicknameTitleM;
    default:
      return NicknameTitleA;
  }
};

export const getColorMainframe = (
  color: ColorType,
  isEnchantment = false,
  isArtifact = false,
  isVehicle = false,
): ImageResData | string => {
  // A colorless artifact uses the artefact frame instead of the plain colorless frame.
  if (isArtifact) {
    if (isEnchantment) {
      return { highRes: ArtefactNyxMainframe, lowRes: LowResArtefactMainframeNyx };
    }
    return isVehicle
      ? { highRes: VehicleMainframe, lowRes: LowResVehicleMainframe }
      : {
          highRes: ArtefactMainframe,
          lowRes: LowResArtefactMainframe,
        };
  }
  switch (color) {
    case ColorType.White:
      return isEnchantment
        ? {
            highRes: WhiteNyxMainframe,
            lowRes: LowResWhiteMainframeNyx,
          }
        : { highRes: WhiteMainframe, lowRes: LowResWhiteMainframe };
    case ColorType.Blue:
      return isEnchantment
        ? {
            highRes: BlueNyxMainframe,
            lowRes: LowResBlueMainframeNyx,
          }
        : { highRes: BlueMainframe, lowRes: LowResBlueMainframe };
    case ColorType.Black:
      return isEnchantment
        ? {
            highRes: BlackNyxMainframe,
            lowRes: LowResBlackMainframeNyx,
          }
        : { highRes: BlackMainframe, lowRes: LowResBlackMainframe };
    case ColorType.Red:
      return isEnchantment
        ? { highRes: RedNyxMainframe, lowRes: LowResRedMainframeNyx }
        : {
            highRes: RedMainframe,
            lowRes: LowResRedMainframe,
          };
    case ColorType.Green:
      return isEnchantment
        ? {
            highRes: GreenNyxMainframe,
            lowRes: LowResGreenMainframeNyx,
          }
        : { highRes: GreenMainframe, lowRes: LowResGreenMainframe };
    case ColorType.Gold:
      return isEnchantment
        ? {
            highRes: GoldNyxMainframe,
            lowRes: LowResGoldMainframeNyx,
          }
        : { highRes: GoldMainframe, lowRes: LowResGoldMainframe };
    default:
      return isEnchantment
        ? {
            highRes: ColorlessNyxMainframe,
            lowRes: LowResColorlessMainframeNyx,
          }
        : { highRes: ColorlessMainframe, lowRes: LowResColorlessMainframe };
  }
};

export const getBorderlessMainframe = (
  color: ColorType,
  isLand = false,
  isArtifact = false,
  isNickname = false,
) => {
  if (isArtifact) {
    return isNickname ? BorderlessNicknameFrameA : BorderlessFrameA;
  }
  if (isLand && color === ColorType.Colorless) {
    return isNickname ? BorderlessNicknameFrameL : BorderlessFrameL;
  }

  switch (color) {
    case ColorType.White:
      return isNickname ? BorderlessNicknameFrameW : BorderlessFrameW;
    case ColorType.Blue:
      return isNickname ? BorderlessNicknameFrameU : BorderlessFrameU;
    case ColorType.Black:
      return isNickname ? BorderlessNicknameFrameB : BorderlessFrameB;
    case ColorType.Red:
      return isNickname ? BorderlessNicknameFrameR : BorderlessFrameR;
    case ColorType.Green:
      return isNickname ? BorderlessNicknameFrameG : BorderlessFrameG;
    case ColorType.Gold:
      return isNickname ? BorderlessNicknameFrameM : BorderlessFrameM;
    default:
      return isNickname ? BorderlessNicknameFrameC : BorderlessFrameC;
  }
};

export const getExtendedMainframe = (
  color: ColorType,
  isLand = false,
  isArtifact = false,
  isVehicle = false,
  isEnchantment = false,
) => {
  if (isArtifact) {
    if (isVehicle) return ExtendedFrameV;
    return isEnchantment ? ExtendedFrameANyx : ExtendedFrameA;
  }
  switch (color) {
    case ColorType.White:
      if (isEnchantment) return ExtendedFrameWNyx;
      return isLand ? ExtendedFrameWL : ExtendedFrameW;
    case ColorType.Blue:
      if (isEnchantment) return ExtendedFrameUNyx;
      return isLand ? ExtendedFrameUL : ExtendedFrameU;
    case ColorType.Black:
      if (isEnchantment) return ExtendedFrameBNyx;
      return isLand ? ExtendedFrameBL : ExtendedFrameB;
    case ColorType.Red:
      if (isEnchantment) return ExtendedFrameRNyx;
      return isLand ? ExtendedFrameRL : ExtendedFrameR;
    case ColorType.Green:
      if (isEnchantment) return ExtendedFrameGNyx;
      return isLand ? ExtendedFrameGL : ExtendedFrameG;
    case ColorType.Gold:
      if (isEnchantment) return ExtendedFrameMNyx;
      return isLand ? ExtendedFrameML : ExtendedFrameM;
    default:
      if (isEnchantment) return ExtendedFrameANyx;
      return isLand ? ExtendedFrameL : ExtendedFrameC;
  }
};

export const getBlack = () => {
  return Black;
};

export const getInnerCrown = (color: ColorType, isArtefact = false) => {
  if (isArtefact) {
    return InnerCrownArtefact;
  }

  switch (color) {
    case ColorType.White:
      return InnerCrownWhite;
    case ColorType.Blue:
      return InnerCrownBlue;
    case ColorType.Black:
      return InnerCrownBlack;
    case ColorType.Red:
      return InnerCrownRed;
    case ColorType.Green:
      return InnerCrownGreen;
    case ColorType.Gold:
      return InnerCrownGold;
    default:
      return InnerCrownArtefact;
  }
};

export const getCrownFloatingExtendedArtFix = () => CrownFloatingExtendedArtFix;
export const getCrownMask = () => CrownMask;

// Keys for the two-color crown combos, in WUBRG wheel order. These match the
// combo variant keys returned by getTwoColorVariant for a two-color card.
type CrownComboKey = 'wu' | 'ub' | 'br' | 'rg' | 'gw' | 'wb' | 'ur' | 'bg' | 'rw' | 'gu';

const CROWN_COMBOS: Record<CrownComboKey, ImageResData> = {
  wu: { highRes: CrownWu, lowRes: CrownWuLowRes },
  ub: { highRes: CrownUb, lowRes: CrownUbLowRes },
  br: { highRes: CrownBr, lowRes: CrownBrLowRes },
  rg: { highRes: CrownRg, lowRes: CrownRgLowRes },
  gw: { highRes: CrownGw, lowRes: CrownGwLowRes },
  wb: { highRes: CrownWb, lowRes: CrownWbLowRes },
  ur: { highRes: CrownUr, lowRes: CrownUrLowRes },
  bg: { highRes: CrownBg, lowRes: CrownBgLowRes },
  rw: { highRes: CrownRw, lowRes: CrownRwLowRes },
  gu: { highRes: CrownGu, lowRes: CrownGuLowRes },
};

const CROWN_FLOATING_COMBOS: Record<CrownComboKey, ImageResData> = {
  wu: { highRes: CrownWuFloating, lowRes: CrownWuFloatingLowRes },
  ub: { highRes: CrownUbFloating, lowRes: CrownUbFloatingLowRes },
  br: { highRes: CrownBrFloating, lowRes: CrownBrFloatingLowRes },
  rg: { highRes: CrownRgFloating, lowRes: CrownRgFloatingLowRes },
  gw: { highRes: CrownGwFloating, lowRes: CrownGwFloatingLowRes },
  wb: { highRes: CrownWbFloating, lowRes: CrownWbFloatingLowRes },
  ur: { highRes: CrownUrFloating, lowRes: CrownUrFloatingLowRes },
  bg: { highRes: CrownBgFloating, lowRes: CrownBgFloatingLowRes },
  rw: { highRes: CrownRwFloating, lowRes: CrownRwFloatingLowRes },
  gu: { highRes: CrownGuFloating, lowRes: CrownGuFloatingLowRes },
};

const CROWN_NICKNAME_COMBOS: Record<CrownComboKey, ImageResData> = {
  wu: { highRes: CrownWuNickname, lowRes: CrownWuNicknameLowRes },
  ub: { highRes: CrownUbNickname, lowRes: CrownUbNicknameLowRes },
  br: { highRes: CrownBrNickname, lowRes: CrownBrNicknameLowRes },
  rg: { highRes: CrownRgNickname, lowRes: CrownRgNicknameLowRes },
  gw: { highRes: CrownGwNickname, lowRes: CrownGwNicknameLowRes },
  wb: { highRes: CrownWbNickname, lowRes: CrownWbNicknameLowRes },
  ur: { highRes: CrownUrNickname, lowRes: CrownUrNicknameLowRes },
  bg: { highRes: CrownBgNickname, lowRes: CrownBgNicknameLowRes },
  rw: { highRes: CrownRwNickname, lowRes: CrownRwNicknameLowRes },
  gu: { highRes: CrownGuNickname, lowRes: CrownGuNicknameLowRes },
};

// Selects the two-color combo crown for an (unordered) color pair, picking the
// style that matches the per-color crown selection: nickname first, then
// floating (full-art), otherwise the base crown.
const getTwoColorCrown = (
  colors: ColorType[],
  isFullart: boolean,
  isNickname: boolean,
): ImageResData => {
  const variant = getTwoColorVariant(colors) as CrownComboKey;
  if (isNickname) return CROWN_NICKNAME_COMBOS[variant];
  if (isFullart) return CROWN_FLOATING_COMBOS[variant];
  return CROWN_COMBOS[variant];
};

export const getCrown = (
  color: ColorType,
  isFullart = false,
  isLand = false,
  isArtefact = false,
  isNickname = false,
  colors: ColorType[] = [],
): ImageResData | string => {
  if (isLand && color === ColorType.Colorless) {
    if (isNickname) return { highRes: CrownLandNickname, lowRes: CrownLandNicknameLowRes };
    return isFullart
      ? { highRes: CrownLandFloating, lowRes: CrownLandFloatingLowRes }
      : { highRes: CrownLand, lowRes: CrownLandLowRes };
  }
  // Non-land cards with exactly two colors use the two-color combo crown,
  // including two-color artifacts, rather than the artefact or gold crown.
  if (colors.length === 2) {
    return getTwoColorCrown(colors, isFullart, isNickname);
  }

  if (isArtefact) {
    if (isNickname) return { highRes: CrownArtefactNickname, lowRes: CrownArtefactNicknameLowRes };
    return isFullart
      ? { highRes: CrownArtefactFloating, lowRes: CrownArtefactFloatingLowRes }
      : { highRes: CrownArtefact, lowRes: CrownArtefactLowRes };
  }

  switch (color) {
    case ColorType.White:
      if (isNickname) return { highRes: CrownWhiteNickname, lowRes: CrownWhiteNicknameLowRes };
      return isFullart
        ? { highRes: CrownWhiteFloating, lowRes: CrownWhiteFloatingLowRes }
        : { highRes: CrownWhite, lowRes: CrownWhiteLowRes };
    case ColorType.Blue:
      if (isNickname) return { highRes: CrownBlueNickname, lowRes: CrownBlueNicknameLowRes };
      return isFullart
        ? { highRes: CrownBlueFloating, lowRes: CrownBlueFloatingLowRes }
        : { highRes: CrownBlue, lowRes: CrownBlueLowRes };
    case ColorType.Black:
      if (isNickname) return { highRes: CrownBlackNickname, lowRes: CrownBlackNicknameLowRes };
      return isFullart
        ? { highRes: CrownBlackFloating, lowRes: CrownBlackFloatingLowRes }
        : { highRes: CrownBlack, lowRes: CrownBlackLowRes };
    case ColorType.Red:
      if (isNickname) return { highRes: CrownRedNickname, lowRes: CrownRedNicknameLowRes };
      return isFullart
        ? { highRes: CrownRedFloating, lowRes: CrownRedFloatingLowRes }
        : { highRes: CrownRed, lowRes: CrownRedLowRes };
    case ColorType.Green:
      if (isNickname) return { highRes: CrownGreenNickname, lowRes: CrownGreenNicknameLowRes };
      return isFullart
        ? { highRes: CrownGreenFloating, lowRes: CrownGreenFloatingLowRes }
        : { highRes: CrownGreen, lowRes: CrownGreenLowRes };
    case ColorType.Gold:
      if (isNickname) return { highRes: CrownGoldNickname, lowRes: CrownGoldNicknameLowRes };
      return isFullart
        ? { highRes: CrownGoldFloating, lowRes: CrownGoldFloatingLowRes }
        : { highRes: CrownGold, lowRes: CrownGoldLowRes };
    default:
      if (isNickname)
        return { highRes: CrownColorlessNickname, lowRes: CrownColorlessNicknameLowRes };
      return isFullart
        ? { highRes: CrownColorlessFloating, lowRes: CrownColorlessFloatingLowRes }
        : { highRes: CrownColorless, lowRes: CrownColorlessLowRes };
  }
};

export const getTokenMainframe = (color: ColorType, isArtifact = false) => {
  if (isArtifact && color === ColorType.Colorless) return TokenArtefactMainframe;
  switch (color) {
    case ColorType.White:
      return TokenWhiteMainframe;
    case ColorType.Blue:
      return TokenBlueMainframe;
    case ColorType.Black:
      return TokenBlackMainframe;
    case ColorType.Red:
      return TokenRedMainframe;
    case ColorType.Green:
      return TokenGreenMainframe;
    case ColorType.Gold:
      return TokenGoldMainframe;
    default:
      return TokenColorlessMainframe;
  }
};

export const getLoyaltyIcon = (loyaltyAction?: string) => {
  if (!loyaltyAction) return '';
  if (loyaltyAction.indexOf('+') !== -1) return LoyaltyUp;
  if (loyaltyAction.indexOf('-') !== -1) return LoyaltyDown;
  if (loyaltyAction === '0') return LoyaltyZero;
  return '';
};

export const getPlaneswalkerPt = () => PlaneswalkerPt;

export const getPlaneswalkerMainframe = (color: ColorType, lines: 2 | 3 | 4 | undefined) => {
  switch (color) {
    case ColorType.White:
      if (lines === 2) return PlaneswalkerWhiteMainframe2;
      if (lines === 4) return PlaneswalkerWhiteMainframe4;
      return PlaneswalkerWhiteMainframe;
    case ColorType.Blue:
      if (lines === 2) return PlaneswalkerBlueMainframe2;
      if (lines === 4) return PlaneswalkerBlueMainframe4;
      return PlaneswalkerBlueMainframe;
    case ColorType.Black:
      if (lines === 2) return PlaneswalkerBlackMainframe2;
      if (lines === 4) return PlaneswalkerBlackMainframe4;
      return PlaneswalkerBlackMainframe;
    case ColorType.Red:
      if (lines === 2) return PlaneswalkerRedMainframe2;
      if (lines === 4) return PlaneswalkerRedMainframe4;
      return PlaneswalkerRedMainframe;
    case ColorType.Green:
      if (lines === 2) return PlaneswalkerGreenMainframe2;
      if (lines === 4) return PlaneswalkerGreenMainframe4;
      return PlaneswalkerGreenMainframe;
    case ColorType.Colorless:
      if (lines === 2) return PlaneswalkerColorlessMainframe2;
      if (lines === 4) return PlaneswalkerColorlessMainframe4;
      return PlaneswalkerColorlessMainframe;
    default:
      if (lines === 2) return PlaneswalkerGoldMainframe2;
      if (lines === 4) return PlaneswalkerGoldMainframe4;
      return PlaneswalkerGoldMainframe;
  }
};

export const getInvocationPt = () => InvocationPt;

export const getInventionPt = () => InventionPt;

export const getInventionMainframe = (color: ColorType, isArtifact = false) => {
  if (isArtifact && color === ColorType.Colorless) return InventionArtefactMainframe;
  switch (color) {
    case ColorType.White:
      return InventionWhiteMainframe;
    case ColorType.Blue:
      return InventionBlueMainframe;
    case ColorType.Black:
      return InventionBlackMainframe;
    case ColorType.Red:
      return InventionRedMainframe;
    case ColorType.Green:
      return InventionGreenMainframe;
    case ColorType.Gold:
      return InventionGoldMainframe;
    default:
      return InventionColorlessMainframe;
  }
};

export const getInvocationMainframe = (color: ColorType) => {
  switch (color) {
    case ColorType.White:
      return InvocationWhiteMainframe;
    case ColorType.Blue:
      return InvocationBlueMainframe;
    case ColorType.Black:
      return InvocationBlackMainframe;
    case ColorType.Red:
      return InvocationRedMainframe;
    case ColorType.Green:
      return InvocationGreenMainframe;
    default:
      return InvocationGoldMainframe;
  }
};

// Maps an unordered pair of colors to its two-color pinline asset. The combo
// files are named in WUBRG wheel order (wu, ub, br, rg, gw, wb, ur, bg, rw, gu),
// so we normalize here regardless of the order the colors arrive in.
const getTwoColorPinline = (colors: ColorType[]) => {
  if (colors.includes(ColorType.White)) {
    if (colors.includes(ColorType.Blue)) return WhiteBluePinline;
    if (colors.includes(ColorType.Black)) return WhiteBlackPinline;
  }
  if (colors.includes(ColorType.Blue)) {
    if (colors.includes(ColorType.Black)) return BlueBlackPinline;
    if (colors.includes(ColorType.Red)) return BlueRedPinline;
  }
  if (colors.includes(ColorType.Black)) {
    if (colors.includes(ColorType.Green)) return BlackGreenPinline;
    if (colors.includes(ColorType.Red)) return BlackRedPinline;
  }
  if (colors.includes(ColorType.Red)) {
    if (colors.includes(ColorType.Green)) return RedGreenPinline;
    if (colors.includes(ColorType.White)) return RedWhitePinline;
  }
  if (colors.includes(ColorType.Green)) {
    if (colors.includes(ColorType.Blue)) return GreenBluePinline;
    if (colors.includes(ColorType.White)) return GreenWhitePinline;
  }
  return GoldPinline;
};

const getSingleColorPinline = (color: ColorType) => {
  if (color === ColorType.White) return WhitePinline;
  if (color === ColorType.Blue) return BluePinline;
  if (color === ColorType.Black) return BlackPinline;
  if (color === ColorType.Red) return RedPinline;
  if (color === ColorType.Green) return GreenPinline;
  return GoldPinline;
};

// Pinlines render only on:
//  - artifacts that are not colorless (pinline matches the card's colors)
//  - non-artifact gold cards with exactly two colors (two-color combo pinline)
// Everything else returns '' (no pinline layer).
//
// For the extended and borderless art styles, only two-color combination
// pinlines were generated (from those styles' own frames); every other case
// gets no pinline instead of falling back to the regular m15-carved assets.
export const getPinline = (
  colors: ColorType[],
  isArtifact: boolean,
  artStyle?: BasicLandArtStyles | CardArtStyles,
) => {
  const variantPinlines =
    artStyle === CardArtStyles.Extended
      ? EXTENDED_PINLINES
      : artStyle === CardArtStyles.Borderless
        ? BORDERLESS_PINLINES
        : null;

  if (variantPinlines) {
    if (colors.length === 2) return variantPinlines[getTwoColorVariant(colors)];
    return '';
  }

  if (isArtifact) {
    if (colors.length === 0) return '';
    if (colors.length === 1) return getSingleColorPinline(colors[0]);
    if (colors.length === 2) return getTwoColorPinline(colors);
    return GoldPinline;
  }

  if (colors.length === 2) return getTwoColorPinline(colors);

  return '';
};

// Variant key shared by the title / type / rules frame parts. '' means no part.
type PartVariant =
  | ''
  | 'w'
  | 'u'
  | 'b'
  | 'r'
  | 'g'
  | 'm'
  | 'wu'
  | 'ub'
  | 'br'
  | 'rg'
  | 'gw'
  | 'wb'
  | 'ur'
  | 'bg'
  | 'rw'
  | 'gu';

// Maps an unordered color pair to its combo variant key (WUBRG wheel order).
const getTwoColorVariant = (colors: ColorType[]): PartVariant => {
  if (colors.includes(ColorType.White)) {
    if (colors.includes(ColorType.Blue)) return 'wu';
    if (colors.includes(ColorType.Black)) return 'wb';
  }
  if (colors.includes(ColorType.Blue)) {
    if (colors.includes(ColorType.Black)) return 'ub';
    if (colors.includes(ColorType.Red)) return 'ur';
  }
  if (colors.includes(ColorType.Black)) {
    if (colors.includes(ColorType.Green)) return 'bg';
    if (colors.includes(ColorType.Red)) return 'br';
  }
  if (colors.includes(ColorType.Red)) {
    if (colors.includes(ColorType.Green)) return 'rg';
    if (colors.includes(ColorType.White)) return 'rw';
  }
  if (colors.includes(ColorType.Green)) {
    if (colors.includes(ColorType.Blue)) return 'gu';
    if (colors.includes(ColorType.White)) return 'gw';
  }
  return 'm';
};

const getSingleColorVariant = (color: ColorType): PartVariant => {
  if (color === ColorType.White) return 'w';
  if (color === ColorType.Blue) return 'u';
  if (color === ColorType.Black) return 'b';
  if (color === ColorType.Red) return 'r';
  if (color === ColorType.Green) return 'g';
  return 'm';
};

// Selection logic for the rules (text box) frame part:
//  - artifacts (non-colorless): part matches the card's colors
//      (single color, two-color combo, or gold for 3+)
//  - non-artifact cards with exactly two colors: golden ('m') part
//  - everything else: no part ('')
// Note this differs from the pinline for two-color non-artifacts, which the
// user wants rendered as the golden part rather than the two-color combo.
const getRulesVariant = (colors: ColorType[], isArtifact: boolean): PartVariant => {
  if (isArtifact) {
    if (colors.length === 0) return '';
    if (colors.length === 1) return getSingleColorVariant(colors[0]);
    if (colors.length === 2) return getTwoColorVariant(colors);
    return 'm';
  }

  if (colors.length === 2) return 'm';

  return '';
};

// Selection logic for the title and type frame parts. Unlike the rules part,
// these never use the two-color combo: any multicolor artifact (two-color or
// 3+) uses the golden ('m') part, as do two-color non-artifact cards.
const getTitleTypeVariant = (colors: ColorType[], isArtifact: boolean): PartVariant => {
  if (isArtifact) {
    if (colors.length === 0) return '';
    if (colors.length === 1) return getSingleColorVariant(colors[0]);
    return 'm';
  }

  if (colors.length === 2) return 'm';

  return '';
};

const TITLE_PARTS: Record<PartVariant, string> = {
  '': '',
  w: WhiteTitle,
  u: BlueTitle,
  b: BlackTitle,
  r: RedTitle,
  g: GreenTitle,
  m: GoldTitle,
  wu: WhiteBlueTitle,
  ub: BlueBlackTitle,
  br: BlackRedTitle,
  rg: RedGreenTitle,
  gw: GreenWhiteTitle,
  wb: WhiteBlackTitle,
  ur: BlueRedTitle,
  bg: BlackGreenTitle,
  rw: RedWhiteTitle,
  gu: GreenBlueTitle,
};

const TYPE_PARTS: Record<PartVariant, string> = {
  '': '',
  w: WhiteType,
  u: BlueType,
  b: BlackType,
  r: RedType,
  g: GreenType,
  m: GoldType,
  wu: WhiteBlueType,
  ub: BlueBlackType,
  br: BlackRedType,
  rg: RedGreenType,
  gw: GreenWhiteType,
  wb: WhiteBlackType,
  ur: BlueRedType,
  bg: BlackGreenType,
  rw: RedWhiteType,
  gu: GreenBlueType,
};

const RULES_PARTS: Record<PartVariant, string> = {
  '': '',
  w: WhiteRules,
  u: BlueRules,
  b: BlackRules,
  r: RedRules,
  g: GreenRules,
  m: GoldRules,
  wu: WhiteBlueRules,
  ub: BlueBlackRules,
  br: BlackRedRules,
  rg: RedGreenRules,
  gw: GreenWhiteRules,
  wb: WhiteBlackRules,
  ur: BlueRedRules,
  bg: BlackGreenRules,
  rw: RedWhiteRules,
  gu: GreenBlueRules,
};

// Pinline variants generated from the extended / borderless frames. Only the
// two-color combinations exist; non-combo keys map to ''.
const EXTENDED_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: ExtendedWhiteBluePinline,
  ub: ExtendedBlueBlackPinline,
  br: ExtendedBlackRedPinline,
  rg: ExtendedRedGreenPinline,
  gw: ExtendedGreenWhitePinline,
  wb: ExtendedWhiteBlackPinline,
  ur: ExtendedBlueRedPinline,
  bg: ExtendedBlackGreenPinline,
  rw: ExtendedRedWhitePinline,
  gu: ExtendedGreenBluePinline,
};

const BORDERLESS_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: BorderlessWhiteBluePinline,
  ub: BorderlessBlueBlackPinline,
  br: BorderlessBlackRedPinline,
  rg: BorderlessRedGreenPinline,
  gw: BorderlessGreenWhitePinline,
  wb: BorderlessWhiteBlackPinline,
  ur: BorderlessBlueRedPinline,
  bg: BorderlessBlackGreenPinline,
  rw: BorderlessRedWhitePinline,
  gu: BorderlessGreenBluePinline,
};

export const getTitlePart = (colors: ColorType[], isArtifact: boolean) =>
  TITLE_PARTS[getTitleTypeVariant(colors, isArtifact)];

export const getTypePart = (colors: ColorType[], isArtifact: boolean) =>
  TYPE_PARTS[getTitleTypeVariant(colors, isArtifact)];

export const getRulesPart = (colors: ColorType[], isArtifact: boolean) =>
  RULES_PARTS[getRulesVariant(colors, isArtifact)];

// Lands only get frame parts when their card-text color identity has exactly
// two colors: the land ('l') title/type parts plus the two-color text part.
// Single-color, 3+ color, and colorless lands get no parts.
export const getLandTitlePart = (colors: ColorType[]) => (colors.length === 2 ? LandTitle : '');

export const getLandTypePart = (colors: ColorType[]) => (colors.length === 2 ? LandType : '');

export const getLandRulesPart = (colors: ColorType[]) =>
  colors.length === 2 ? RULES_PARTS[getTwoColorVariant(colors)] : '';

export const getLandOverlay = () => LandOverlay;

export const getBasicLandSymbols = (landType: BasicLandType) => {
  switch (landType) {
    case BasicLandType.Plains:
      return SymbolLandWhite;
    case BasicLandType.Island:
      return SymbolLandBlue;
    case BasicLandType.Swamp:
      return SymbolLandBlack;
    case BasicLandType.Mountain:
      return SymbolLandRed;
    case BasicLandType.Forest:
      return SymbolLandGreen;
    default:
      return SymbolLandColorless;
  }
};

export const getLandMainframe = (
  color: ColorType,
  artStyle: BasicLandArtStyles | CardArtStyles | undefined,
): ImageResData | string => {
  switch (color) {
    case ColorType.White:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandWhiteMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandWhiteMainframe;
      return { highRes: LandWhiteMainframe, lowRes: LandWhiteMainframeLowRes };
    case ColorType.Blue:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandBlueMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandBlueMainframe;
      return { highRes: LandBlueMainframe, lowRes: LandBlueMainframeLowRes };
    case ColorType.Black:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandBlackMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandBlackMainframe;
      return { highRes: LandBlackMainframe, lowRes: LandBlackMainframeLowRes };
    case ColorType.Red:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandRedMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandRedMainframe;
      return { highRes: LandRedMainframe, lowRes: LandRedMainframeLowRes };
    case ColorType.Green:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandGreenMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandGreenMainframe;
      return { highRes: LandGreenMainframe, lowRes: LandGreenMainframeLowRes };
    case ColorType.Gold:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandGoldMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandGoldMainframe;
      return { highRes: LandGoldMainframe, lowRes: LandGoldMainframeLowRes };
    default:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandGoldMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandGoldMainframe;
      return { highRes: LandColorlessMainframe, lowRes: LandColorlessMainframeLowRes };
  }
};

export const getRarityIcon = (rarity: RarityType) => {
  if (rarity === RarityType.MythicRare) return MythicRareIcon;
  if (rarity === RarityType.Rare) return RareIcon;
  if (rarity === RarityType.Uncommon) return UncommonIcon;
  return CommonIcon;
};
