import CrownFloatingExtendedArtFix from './images/crown/floating/extendedArtFix.png';
import CrownArtefact from './images/crown/a.png';
import CrownArtefactLowRes from './images/crown/aThumb.png';
import CrownArtefactFloating from './images/crown/floating/a.png';
import CrownColorlessFloating from './images/crown/floating/a.png';
import CrownArtefactFloatingLowRes from './images/crown/floating/aThumb.png';
import CrownColorlessFloatingLowRes from './images/crown/floating/aThumb.png';
import CrownArtefactNickname from './images/crown/nickname/a.png';
import CrownColorlessNickname from './images/crown/nickname/a.png';
import CrownArtefactNicknameLowRes from './images/crown/nickname/aThumb.png';
import CrownColorlessNicknameLowRes from './images/crown/nickname/aThumb.png';
import CrownWhite from './images/crown/w.png';
import CrownWhiteLowRes from './images/crown/wThumb.png';
import CrownWhiteFloating from './images/crown/floating/w.png';
import CrownWhiteFloatingLowRes from './images/crown/floating/wThumb.png';
import CrownWhiteNickname from './images/crown/nickname/w.png';
import CrownWhiteNicknameLowRes from './images/crown/nickname/wThumb.png';
import CrownBlue from './images/crown/u.png';
import CrownBlueLowRes from './images/crown/uThumb.png';
import CrownBlueFloating from './images/crown/floating/u.png';
import CrownBlueFloatingLowRes from './images/crown/floating/uThumb.png';
import CrownBlueNickname from './images/crown/nickname/u.png';
import CrownBlueNicknameLowRes from './images/crown/nickname/uThumb.png';
import CrownBlack from './images/crown/b.png';
import CrownBlackLowRes from './images/crown/bThumb.png';
import CrownBlackFloating from './images/crown/floating/b.png';
import CrownBlackFloatingLowRes from './images/crown/floating/bThumb.png';
import CrownBlackNickname from './images/crown/nickname/b.png';
import CrownBlackNicknameLowRes from './images/crown/nickname/bThumb.png';
import CrownRed from './images/crown/r.png';
import CrownRedLowRes from './images/crown/rThumb.png';
import CrownRedFloating from './images/crown/floating/r.png';
import CrownRedFloatingLowRes from './images/crown/floating/rThumb.png';
import CrownRedNickname from './images/crown/nickname/r.png';
import CrownRedNicknameLowRes from './images/crown/nickname/rThumb.png';
import CrownGreen from './images/crown/g.png';
import CrownGreenLowRes from './images/crown/gThumb.png';
import CrownGreenFloating from './images/crown/floating/g.png';
import CrownGreenFloatingLowRes from './images/crown/floating/gThumb.png';
import CrownGreenNickname from './images/crown/nickname/g.png';
import CrownGreenNicknameLowRes from './images/crown/nickname/gThumb.png';
import CrownGold from './images/crown/m.png';
import CrownGoldLowRes from './images/crown/mThumb.png';
import CrownGoldFloating from './images/crown/floating/m.png';
import CrownGoldFloatingLowRes from './images/crown/floating/mThumb.png';
import CrownGoldNickname from './images/crown/nickname/m.png';
import CrownGoldNicknameLowRes from './images/crown/nickname/mThumb.png';
import CrownLand from './images/crown/l.png';
import CrownLandLowRes from './images/crown/lThumb.png';
import CrownLandFloating from './images/crown/floating/l.png';
import CrownLandFloatingLowRes from './images/crown/floating/lThumb.png';
import CrownLandNickname from './images/crown/nickname/l.png';
import CrownLandNicknameLowRes from './images/crown/nickname/lThumb.png';
import CrownColorless from './images/crown/c.png';
import CrownColorlessLowRes from './images/crown/cThumb.png';
// Two-color crown combos (WUBRG wheel order), for the base, floating (full-art)
// and nickname crown styles. Generated by scripts/generate-parts.cjs.
import CrownWu from './images/crown/wu.png';
import CrownWuLowRes from './images/crown/wuThumb.png';
import CrownWuFloating from './images/crown/floating/wu.png';
import CrownWuFloatingLowRes from './images/crown/floating/wuThumb.png';
import CrownWuNickname from './images/crown/nickname/wu.png';
import CrownWuNicknameLowRes from './images/crown/nickname/wuThumb.png';
import CrownUb from './images/crown/ub.png';
import CrownUbLowRes from './images/crown/ubThumb.png';
import CrownUbFloating from './images/crown/floating/ub.png';
import CrownUbFloatingLowRes from './images/crown/floating/ubThumb.png';
import CrownUbNickname from './images/crown/nickname/ub.png';
import CrownUbNicknameLowRes from './images/crown/nickname/ubThumb.png';
import CrownBr from './images/crown/br.png';
import CrownBrLowRes from './images/crown/brThumb.png';
import CrownBrFloating from './images/crown/floating/br.png';
import CrownBrFloatingLowRes from './images/crown/floating/brThumb.png';
import CrownBrNickname from './images/crown/nickname/br.png';
import CrownBrNicknameLowRes from './images/crown/nickname/brThumb.png';
import CrownRg from './images/crown/rg.png';
import CrownRgLowRes from './images/crown/rgThumb.png';
import CrownRgFloating from './images/crown/floating/rg.png';
import CrownRgFloatingLowRes from './images/crown/floating/rgThumb.png';
import CrownRgNickname from './images/crown/nickname/rg.png';
import CrownRgNicknameLowRes from './images/crown/nickname/rgThumb.png';
import CrownGw from './images/crown/gw.png';
import CrownGwLowRes from './images/crown/gwThumb.png';
import CrownGwFloating from './images/crown/floating/gw.png';
import CrownGwFloatingLowRes from './images/crown/floating/gwThumb.png';
import CrownGwNickname from './images/crown/nickname/gw.png';
import CrownGwNicknameLowRes from './images/crown/nickname/gwThumb.png';
import CrownWb from './images/crown/wb.png';
import CrownWbLowRes from './images/crown/wbThumb.png';
import CrownWbFloating from './images/crown/floating/wb.png';
import CrownWbFloatingLowRes from './images/crown/floating/wbThumb.png';
import CrownWbNickname from './images/crown/nickname/wb.png';
import CrownWbNicknameLowRes from './images/crown/nickname/wbThumb.png';
import CrownUr from './images/crown/ur.png';
import CrownUrLowRes from './images/crown/urThumb.png';
import CrownUrFloating from './images/crown/floating/ur.png';
import CrownUrFloatingLowRes from './images/crown/floating/urThumb.png';
import CrownUrNickname from './images/crown/nickname/ur.png';
import CrownUrNicknameLowRes from './images/crown/nickname/urThumb.png';
import CrownBg from './images/crown/bg.png';
import CrownBgLowRes from './images/crown/bgThumb.png';
import CrownBgFloating from './images/crown/floating/bg.png';
import CrownBgFloatingLowRes from './images/crown/floating/bgThumb.png';
import CrownBgNickname from './images/crown/nickname/bg.png';
import CrownBgNicknameLowRes from './images/crown/nickname/bgThumb.png';
import CrownRw from './images/crown/rw.png';
import CrownRwLowRes from './images/crown/rwThumb.png';
import CrownRwFloating from './images/crown/floating/rw.png';
import CrownRwFloatingLowRes from './images/crown/floating/rwThumb.png';
import CrownRwNickname from './images/crown/nickname/rw.png';
import CrownRwNicknameLowRes from './images/crown/nickname/rwThumb.png';
import CrownGu from './images/crown/gu.png';
import CrownGuLowRes from './images/crown/guThumb.png';
import CrownGuFloating from './images/crown/floating/gu.png';
import CrownGuFloatingLowRes from './images/crown/floating/guThumb.png';
import CrownGuNickname from './images/crown/nickname/gu.png';
import CrownGuNicknameLowRes from './images/crown/nickname/guThumb.png';
import InnerCrownArtefact from './images/crown/m15InnerCrownANyx.png';
import InnerCrownWhite from './images/crown/m15InnerCrownWNyx.png';
import InnerCrownBlue from './images/crown/m15InnerCrownUNyx.png';
import InnerCrownBlack from './images/crown/m15InnerCrownBNyx.png';
import InnerCrownRed from './images/crown/m15InnerCrownRNyx.png';
import InnerCrownGreen from './images/crown/m15InnerCrownGNyx.png';
import InnerCrownGold from './images/crown/m15InnerCrownMNyx.png';

import Black from './images/black.png';

import VehicleMainframe from './images/mainframes/m15/v.png';
import ArtefactMainframe from './images/mainframes/m15/a.png';
import ArtefactNyxMainframe from './images/mainframes/m15/nyx/a.png';
import ColorlessNyxMainframe from './images/mainframes/m15/nyx/a.png';
import WhiteMainframe from './images/mainframes/m15/w.png';
import WhiteNyxMainframe from './images/mainframes/m15/nyx/w.png';
import BlueMainframe from './images/mainframes/m15/u.png';
import BlueNyxMainframe from './images/mainframes/m15/nyx/u.png';
import BlackMainframe from './images/mainframes/m15/b.png';
import BlackNyxMainframe from './images/mainframes/m15/nyx/b.png';
import RedMainframe from './images/mainframes/m15/r.png';
import RedNyxMainframe from './images/mainframes/m15/nyx/r.png';
import GreenMainframe from './images/mainframes/m15/g.png';
import GreenNyxMainframe from './images/mainframes/m15/nyx/g.png';
import GoldMainframe from './images/mainframes/m15/m.png';
import GoldNyxMainframe from './images/mainframes/m15/nyx/m.png';
import ColorlessMainframe from './images/mainframes/m15/c.png';

import BorderlessFrameA from './images/mainframes/borderless/m15GenericShowcaseFrameA.png';
import BorderlessFrameC from './images/mainframes/borderless/m15GenericShowcaseFrameC.png';
import BorderlessFrameL from './images/mainframes/borderless/m15GenericShowcaseFrameL.png';
import BorderlessFrameW from './images/mainframes/borderless/m15GenericShowcaseFrameW.png';
import BorderlessFrameU from './images/mainframes/borderless/m15GenericShowcaseFrameU.png';
import BorderlessFrameB from './images/mainframes/borderless/m15GenericShowcaseFrameB.png';
import BorderlessFrameR from './images/mainframes/borderless/m15GenericShowcaseFrameR.png';
import BorderlessFrameG from './images/mainframes/borderless/m15GenericShowcaseFrameG.png';
import BorderlessFrameM from './images/mainframes/borderless/m15GenericShowcaseFrameM.png';
import BorderlessFrameALowRes from './images/mainframes/borderless/m15GenericShowcaseFrameAThumb.png';
import BorderlessFrameCLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameCThumb.png';
import BorderlessFrameLLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameLThumb.png';
import BorderlessFrameWLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameWThumb.png';
import BorderlessFrameULowRes from './images/mainframes/borderless/m15GenericShowcaseFrameUThumb.png';
import BorderlessFrameBLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameBThumb.png';
import BorderlessFrameRLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameRThumb.png';
import BorderlessFrameGLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameGThumb.png';
import BorderlessFrameMLowRes from './images/mainframes/borderless/m15GenericShowcaseFrameMThumb.png';
import BorderlessNicknameFrameA from './images/mainframes/borderless/nickname/m15NicknameFrameA.png';
import BorderlessNicknameFrameC from './images/mainframes/borderless/nickname/m15NicknameFrameA.png';
import BorderlessNicknameFrameL from './images/mainframes/borderless/nickname/m15NicknameFrameL.png';
import BorderlessNicknameFrameW from './images/mainframes/borderless/nickname/m15NicknameFrameW.png';
import BorderlessNicknameFrameU from './images/mainframes/borderless/nickname/m15NicknameFrameU.png';
import BorderlessNicknameFrameB from './images/mainframes/borderless/nickname/m15NicknameFrameB.png';
import BorderlessNicknameFrameR from './images/mainframes/borderless/nickname/m15NicknameFrameR.png';
import BorderlessNicknameFrameG from './images/mainframes/borderless/nickname/m15NicknameFrameG.png';
import BorderlessNicknameFrameM from './images/mainframes/borderless/nickname/m15NicknameFrameM.png';

import ExtendedFrameA from './images/mainframes/extended/a.png';
import ExtendedFrameANyx from './images/mainframes/extended/nyx/a.png';
import ExtendedFrameALowRes from './images/mainframes/extended/aThumb.png';
import ExtendedFrameANyxLowRes from './images/mainframes/extended/nyx/aThumb.png';
import ExtendedFrameV from './images/mainframes/extended/v.png';
import ExtendedFrameVLowRes from './images/mainframes/extended/vThumb.png';
import ExtendedFrameC from './images/mainframes/extended/c.png';
import ExtendedFrameCLowRes from './images/mainframes/extended/cThumb.png';
import ExtendedFrameL from './images/mainframes/extended/l.png';
import ExtendedFrameLLowRes from './images/mainframes/extended/lThumb.png';
import ExtendedFrameWNyx from './images/mainframes/extended/nyx/w.png';
import ExtendedFrameWNyxLowRes from './images/mainframes/extended/nyx/wThumb.png';
import ExtendedFrameW from './images/mainframes/extended/w.png';
import ExtendedFrameWLowRes from './images/mainframes/extended/wThumb.png';
import ExtendedFrameWL from './images/mainframes/extended/lw.png';
import ExtendedFrameWLLowRes from './images/mainframes/extended/lwThumb.png';
import ExtendedFrameU from './images/mainframes/extended/u.png';
import ExtendedFrameUNyx from './images/mainframes/extended/nyx/u.png';
import ExtendedFrameULowRes from './images/mainframes/extended/uThumb.png';
import ExtendedFrameUNyxLowRes from './images/mainframes/extended/nyx/uThumb.png';
import ExtendedFrameUL from './images/mainframes/extended/lu.png';
import ExtendedFrameULLowRes from './images/mainframes/extended/luThumb.png';
import ExtendedFrameB from './images/mainframes/extended/b.png';
import ExtendedFrameBNyx from './images/mainframes/extended/nyx/b.png';
import ExtendedFrameBLowRes from './images/mainframes/extended/bThumb.png';
import ExtendedFrameBNyxLowRes from './images/mainframes/extended/nyx/bThumb.png';
import ExtendedFrameBL from './images/mainframes/extended/lb.png';
import ExtendedFrameBLLowRes from './images/mainframes/extended/lbThumb.png';
import ExtendedFrameR from './images/mainframes/extended/r.png';
import ExtendedFrameRNyx from './images/mainframes/extended/nyx/r.png';
import ExtendedFrameRLowRes from './images/mainframes/extended/rThumb.png';
import ExtendedFrameRNyxLowRes from './images/mainframes/extended/nyx/rThumb.png';
import ExtendedFrameRL from './images/mainframes/extended/lr.png';
import ExtendedFrameRLLowRes from './images/mainframes/extended/lrThumb.png';
import ExtendedFrameG from './images/mainframes/extended/g.png';
import ExtendedFrameGNyx from './images/mainframes/extended/nyx/g.png';
import ExtendedFrameGLowRes from './images/mainframes/extended/gThumb.png';
import ExtendedFrameGNyxLowRes from './images/mainframes/extended/nyx/gThumb.png';
import ExtendedFrameGL from './images/mainframes/extended/lg.png';
import ExtendedFrameGLLowRes from './images/mainframes/extended/lgThumb.png';
import ExtendedFrameM from './images/mainframes/extended/m.png';
import ExtendedFrameMNyx from './images/mainframes/extended/nyx/m.png';
import ExtendedFrameMLowRes from './images/mainframes/extended/mThumb.png';
import ExtendedFrameMNyxLowRes from './images/mainframes/extended/nyx/mThumb.png';
import ExtendedFrameML from './images/mainframes/extended/lm.png';
import ExtendedFrameMLLowRes from './images/mainframes/extended/lmThumb.png';

import TokenArtefactMainframe from './images/mainframes/token/tokenFrameAShort.png';
import TokenArtefactMainframeLowRes from './images/mainframes/token/tokenFrameAShortThumb.png';
import TokenColorlessMainframe from './images/mainframes/token/frameC.png';
import TokenColorlessMainframeLowRes from './images/mainframes/token/frameCThumb.png';
import TokenLandMainframe from './images/mainframes/token/tokenFrameLShort.png';
import TokenLandMainframeLowRes from './images/mainframes/token/tokenFrameLShortThumb.png';
import TokenWhiteMainframe from './images/mainframes/token/tokenFrameWShort.png';
import TokenWhiteMainframeLowRes from './images/mainframes/token/tokenFrameWShortThumb.png';
import TokenBlueMainframe from './images/mainframes/token/tokenFrameUShort.png';
import TokenBlueMainframeLowRes from './images/mainframes/token/tokenFrameUShortThumb.png';
import TokenBlackMainframe from './images/mainframes/token/tokenFrameBShort.png';
import TokenBlackMainframeLowRes from './images/mainframes/token/tokenFrameBShortThumb.png';
import TokenRedMainframe from './images/mainframes/token/tokenFrameRShort.png';
import TokenRedMainframeLowRes from './images/mainframes/token/tokenFrameRShortThumb.png';
import TokenGreenMainframe from './images/mainframes/token/tokenFrameGShort.png';
import TokenGreenMainframeLowRes from './images/mainframes/token/tokenFrameGShortThumb.png';
import TokenGoldMainframe from './images/mainframes/token/tokenFrameMShort.png';
import TokenGoldMainframeLowRes from './images/mainframes/token/tokenFrameMShortThumb.png';

import InvocationWhiteMainframe from './images/mainframes/invocation/W.png';
import InvocationBlueMainframe from './images/mainframes/invocation/U.png';
import InvocationBlackMainframe from './images/mainframes/invocation/B.png';
import InvocationRedMainframe from './images/mainframes/invocation/R.png';
import InvocationGreenMainframe from './images/mainframes/invocation/G.png';
import InvocationGoldMainframe from './images/mainframes/invocation/Gld.png';

import InventionArtefactMainframe from './images/mainframes/invention/a.png';
import InventionColorlessMainframe from './images/mainframes/invention/l.png';
import InventionWhiteMainframe from './images/mainframes/invention/w.png';
import InventionBlueMainframe from './images/mainframes/invention/u.png';
import InventionBlackMainframe from './images/mainframes/invention/b.png';
import InventionRedMainframe from './images/mainframes/invention/r.png';
import InventionGreenMainframe from './images/mainframes/invention/g.png';
import InventionGoldMainframe from './images/mainframes/invention/m.png';

import LowResWhiteMainframe from './images/mainframes/m15/wThumb.png';
import LowResBlueMainframe from './images/mainframes/m15/uThumb.png';
import LowResBlackMainframe from './images/mainframes/m15/bThumb.png';
import LowResRedMainframe from './images/mainframes/m15/rThumb.png';
import LowResGreenMainframe from './images/mainframes/m15/gThumb.png';
import LowResGoldMainframe from './images/mainframes/m15/mThumb.png';
import LowResColorlessMainframe from './images/mainframes/m15/cThumb.png';
import LowResArtefactMainframe from './images/mainframes/m15/aThumb.png';
import LowResVehicleMainframe from './images/mainframes/m15/vThumb.png';

import LowResWhiteMainframeNyx from './images/mainframes/m15/nyx/wThumb.png';
import LowResBlueMainframeNyx from './images/mainframes/m15/nyx/uThumb.png';
import LowResBlackMainframeNyx from './images/mainframes/m15/nyx/bThumb.png';
import LowResRedMainframeNyx from './images/mainframes/m15/nyx/rThumb.png';
import LowResGreenMainframeNyx from './images/mainframes/m15/nyx/gThumb.png';
import LowResGoldMainframeNyx from './images/mainframes/m15/nyx/mThumb.png';
import LowResColorlessMainframeNyx from './images/mainframes/m15/nyx/aThumb.png';
import LowResArtefactMainframeNyx from './images/mainframes/m15/nyx/aThumb.png';

import UnstableBasicLandWhiteMainframe from './images/mainframes/lands/unstable/W.png';
import UnstableBasicLandBlueMainframe from './images/mainframes/lands/unstable/U.png';
import UnstableBasicLandBlackMainframe from './images/mainframes/lands/unstable/B.png';
import UnstableBasicLandRedMainframe from './images/mainframes/lands/unstable/R.png';
import UnstableBasicLandGreenMainframe from './images/mainframes/lands/unstable/G.png';
import UnstableBasicLandGoldMainframe from './images/mainframes/lands/unstable/Gld.png';

import FullArtBasicLandWhiteMainframe from './images/mainframes/lands/fullArt/W.png';
import FullArtBasicLandBlueMainframe from './images/mainframes/lands/fullArt/U.png';
import FullArtBasicLandBlackMainframe from './images/mainframes/lands/fullArt/B.png';
import FullArtBasicLandRedMainframe from './images/mainframes/lands/fullArt/R.png';
import FullArtBasicLandGreenMainframe from './images/mainframes/lands/fullArt/G.png';
import FullArtBasicLandGoldMainframe from './images/mainframes/lands/fullArt/A.png';

import LandWhiteMainframe from './images/mainframes/lands/lw.png';
import LandBlueMainframe from './images/mainframes/lands/lu.png';
import LandBlackMainframe from './images/mainframes/lands/lb.png';
import LandRedMainframe from './images/mainframes/lands/lr.png';
import LandGreenMainframe from './images/mainframes/lands/lg.png';
import LandGoldMainframe from './images/mainframes/lands/lm.png';
import LandColorlessMainframe from './images/mainframes/lands/l.png';
import LandWhiteMainframeLowRes from './images/mainframes/lands/lwThumb.png';
import LandBlueMainframeLowRes from './images/mainframes/lands/luThumb.png';
import LandBlackMainframeLowRes from './images/mainframes/lands/lbThumb.png';
import LandRedMainframeLowRes from './images/mainframes/lands/lrThumb.png';
import LandGreenMainframeLowRes from './images/mainframes/lands/lgThumb.png';
import LandGoldMainframeLowRes from './images/mainframes/lands/lmThumb.png';
import LandColorlessMainframeLowRes from './images/mainframes/lands/lThumb.png';

import WhitePinline from './images/parts/pinline/w.png';
import BluePinline from './images/parts/pinline/u.png';
import BlackPinline from './images/parts/pinline/b.png';
import RedPinline from './images/parts/pinline/r.png';
import GreenPinline from './images/parts/pinline/g.png';
import GoldPinline from './images/parts/pinline/m.png';
import WhiteBluePinline from './images/parts/pinline/wu.png';
import BlueBlackPinline from './images/parts/pinline/ub.png';
import BlackRedPinline from './images/parts/pinline/br.png';
import RedGreenPinline from './images/parts/pinline/rg.png';
import GreenWhitePinline from './images/parts/pinline/gw.png';
import WhiteBlackPinline from './images/parts/pinline/wb.png';
import BlueRedPinline from './images/parts/pinline/ur.png';
import BlackGreenPinline from './images/parts/pinline/bg.png';
import RedWhitePinline from './images/parts/pinline/rw.png';
import GreenBluePinline from './images/parts/pinline/gu.png';

import ExtendedWhiteBluePinline from './images/parts/pinline/extended/wu.png';
import ExtendedBlueBlackPinline from './images/parts/pinline/extended/ub.png';
import ExtendedBlackRedPinline from './images/parts/pinline/extended/br.png';
import ExtendedRedGreenPinline from './images/parts/pinline/extended/rg.png';
import ExtendedGreenWhitePinline from './images/parts/pinline/extended/gw.png';
import ExtendedWhiteBlackPinline from './images/parts/pinline/extended/wb.png';
import ExtendedBlueRedPinline from './images/parts/pinline/extended/ur.png';
import ExtendedBlackGreenPinline from './images/parts/pinline/extended/bg.png';
import ExtendedRedWhitePinline from './images/parts/pinline/extended/rw.png';
import ExtendedGreenBluePinline from './images/parts/pinline/extended/gu.png';

import BorderlessWhiteBluePinline from './images/parts/pinline/borderless/wu.png';
import BorderlessBlueBlackPinline from './images/parts/pinline/borderless/ub.png';
import BorderlessBlackRedPinline from './images/parts/pinline/borderless/br.png';
import BorderlessRedGreenPinline from './images/parts/pinline/borderless/rg.png';
import BorderlessGreenWhitePinline from './images/parts/pinline/borderless/gw.png';
import BorderlessWhiteBlackPinline from './images/parts/pinline/borderless/wb.png';
import BorderlessBlueRedPinline from './images/parts/pinline/borderless/ur.png';
import BorderlessBlackGreenPinline from './images/parts/pinline/borderless/bg.png';
import BorderlessRedWhitePinline from './images/parts/pinline/borderless/rw.png';
import BorderlessGreenBluePinline from './images/parts/pinline/borderless/gu.png';

import PwRegularWhiteBluePinline from './images/parts/pinline/planeswalker/regular/wu.png';
import PwRegularBlueBlackPinline from './images/parts/pinline/planeswalker/regular/ub.png';
import PwRegularBlackRedPinline from './images/parts/pinline/planeswalker/regular/br.png';
import PwRegularRedGreenPinline from './images/parts/pinline/planeswalker/regular/rg.png';
import PwRegularGreenWhitePinline from './images/parts/pinline/planeswalker/regular/gw.png';
import PwRegularWhiteBlackPinline from './images/parts/pinline/planeswalker/regular/wb.png';
import PwRegularBlueRedPinline from './images/parts/pinline/planeswalker/regular/ur.png';
import PwRegularBlackGreenPinline from './images/parts/pinline/planeswalker/regular/bg.png';
import PwRegularRedWhitePinline from './images/parts/pinline/planeswalker/regular/rw.png';
import PwRegularGreenBluePinline from './images/parts/pinline/planeswalker/regular/gu.png';

import PwTallWhiteBluePinline from './images/parts/pinline/planeswalker/tall/wu.png';
import PwTallBlueBlackPinline from './images/parts/pinline/planeswalker/tall/ub.png';
import PwTallBlackRedPinline from './images/parts/pinline/planeswalker/tall/br.png';
import PwTallRedGreenPinline from './images/parts/pinline/planeswalker/tall/rg.png';
import PwTallGreenWhitePinline from './images/parts/pinline/planeswalker/tall/gw.png';
import PwTallWhiteBlackPinline from './images/parts/pinline/planeswalker/tall/wb.png';
import PwTallBlueRedPinline from './images/parts/pinline/planeswalker/tall/ur.png';
import PwTallBlackGreenPinline from './images/parts/pinline/planeswalker/tall/bg.png';
import PwTallRedWhitePinline from './images/parts/pinline/planeswalker/tall/rw.png';
import PwTallGreenBluePinline from './images/parts/pinline/planeswalker/tall/gu.png';

import PwBorderlessWhiteBluePinline from './images/parts/pinline/planeswalker/borderless/wu.png';
import PwBorderlessBlueBlackPinline from './images/parts/pinline/planeswalker/borderless/ub.png';
import PwBorderlessBlackRedPinline from './images/parts/pinline/planeswalker/borderless/br.png';
import PwBorderlessRedGreenPinline from './images/parts/pinline/planeswalker/borderless/rg.png';
import PwBorderlessGreenWhitePinline from './images/parts/pinline/planeswalker/borderless/gw.png';
import PwBorderlessWhiteBlackPinline from './images/parts/pinline/planeswalker/borderless/wb.png';
import PwBorderlessBlueRedPinline from './images/parts/pinline/planeswalker/borderless/ur.png';
import PwBorderlessBlackGreenPinline from './images/parts/pinline/planeswalker/borderless/bg.png';
import PwBorderlessRedWhitePinline from './images/parts/pinline/planeswalker/borderless/rw.png';
import PwBorderlessGreenBluePinline from './images/parts/pinline/planeswalker/borderless/gu.png';

import PwTallBorderlessWhiteBluePinline from './images/parts/pinline/planeswalker/tallBorderless/wu.png';
import PwTallBorderlessBlueBlackPinline from './images/parts/pinline/planeswalker/tallBorderless/ub.png';
import PwTallBorderlessBlackRedPinline from './images/parts/pinline/planeswalker/tallBorderless/br.png';
import PwTallBorderlessRedGreenPinline from './images/parts/pinline/planeswalker/tallBorderless/rg.png';
import PwTallBorderlessGreenWhitePinline from './images/parts/pinline/planeswalker/tallBorderless/gw.png';
import PwTallBorderlessWhiteBlackPinline from './images/parts/pinline/planeswalker/tallBorderless/wb.png';
import PwTallBorderlessBlueRedPinline from './images/parts/pinline/planeswalker/tallBorderless/ur.png';
import PwTallBorderlessBlackGreenPinline from './images/parts/pinline/planeswalker/tallBorderless/bg.png';
import PwTallBorderlessRedWhitePinline from './images/parts/pinline/planeswalker/tallBorderless/rw.png';
import PwTallBorderlessGreenBluePinline from './images/parts/pinline/planeswalker/tallBorderless/gu.png';

import WhiteTitle from './images/parts/title/w.png';
import BlueTitle from './images/parts/title/u.png';
import BlackTitle from './images/parts/title/b.png';
import RedTitle from './images/parts/title/r.png';
import GreenTitle from './images/parts/title/g.png';
import GoldTitle from './images/parts/title/m.png';
import WhiteBlueTitle from './images/parts/title/wu.png';
import BlueBlackTitle from './images/parts/title/ub.png';
import BlackRedTitle from './images/parts/title/br.png';
import RedGreenTitle from './images/parts/title/rg.png';
import GreenWhiteTitle from './images/parts/title/gw.png';
import WhiteBlackTitle from './images/parts/title/wb.png';
import BlueRedTitle from './images/parts/title/ur.png';
import BlackGreenTitle from './images/parts/title/bg.png';
import RedWhiteTitle from './images/parts/title/rw.png';
import GreenBlueTitle from './images/parts/title/gu.png';

import WhiteType from './images/parts/type/w.png';
import BlueType from './images/parts/type/u.png';
import BlackType from './images/parts/type/b.png';
import RedType from './images/parts/type/r.png';
import GreenType from './images/parts/type/g.png';
import GoldType from './images/parts/type/m.png';
import WhiteBlueType from './images/parts/type/wu.png';
import BlueBlackType from './images/parts/type/ub.png';
import BlackRedType from './images/parts/type/br.png';
import RedGreenType from './images/parts/type/rg.png';
import GreenWhiteType from './images/parts/type/gw.png';
import WhiteBlackType from './images/parts/type/wb.png';
import BlueRedType from './images/parts/type/ur.png';
import BlackGreenType from './images/parts/type/bg.png';
import RedWhiteType from './images/parts/type/rw.png';
import GreenBlueType from './images/parts/type/gu.png';

import LandTitle from './images/parts/title/l.png';
import LandType from './images/parts/type/l.png';

import WhiteRules from './images/parts/rules/w.png';
import BlueRules from './images/parts/rules/u.png';
import BlackRules from './images/parts/rules/b.png';
import RedRules from './images/parts/rules/r.png';
import GreenRules from './images/parts/rules/g.png';
import GoldRules from './images/parts/rules/m.png';
import WhiteBlueRules from './images/parts/rules/wu.png';
import BlueBlackRules from './images/parts/rules/ub.png';
import BlackRedRules from './images/parts/rules/br.png';
import RedGreenRules from './images/parts/rules/rg.png';
import GreenWhiteRules from './images/parts/rules/gw.png';
import WhiteBlackRules from './images/parts/rules/wb.png';
import BlueRedRules from './images/parts/rules/ur.png';
import BlackGreenRules from './images/parts/rules/bg.png';
import RedWhiteRules from './images/parts/rules/rw.png';
import GreenBlueRules from './images/parts/rules/gu.png';

// Token frame parts. Only the two-color combinations exist (carved from the
// token frames by scripts/generate-parts.cjs); single colors are rendered as
// the whole token frame instead.
import TokenWhiteBluePinline from './images/parts/tokenPinline/wu.png';
import TokenBlueBlackPinline from './images/parts/tokenPinline/ub.png';
import TokenBlackRedPinline from './images/parts/tokenPinline/br.png';
import TokenRedGreenPinline from './images/parts/tokenPinline/rg.png';
import TokenGreenWhitePinline from './images/parts/tokenPinline/gw.png';
import TokenWhiteBlackPinline from './images/parts/tokenPinline/wb.png';
import TokenBlueRedPinline from './images/parts/tokenPinline/ur.png';
import TokenBlackGreenPinline from './images/parts/tokenPinline/bg.png';
import TokenRedWhitePinline from './images/parts/tokenPinline/rw.png';
import TokenGreenBluePinline from './images/parts/tokenPinline/gu.png';

// Token land type part: carved from the token land frame (tokenFrameLShort.png)
// with the tokenType mask by scripts/generate-parts.cjs.
import TokenLandType from './images/parts/tokenType/l.png';

import TokenWhiteBlueRules from './images/parts/tokenRules/wu.png';
import TokenBlueBlackRules from './images/parts/tokenRules/ub.png';
import TokenBlackRedRules from './images/parts/tokenRules/br.png';
import TokenRedGreenRules from './images/parts/tokenRules/rg.png';
import TokenGreenWhiteRules from './images/parts/tokenRules/gw.png';
import TokenWhiteBlackRules from './images/parts/tokenRules/wb.png';
import TokenBlueRedRules from './images/parts/tokenRules/ur.png';
import TokenBlackGreenRules from './images/parts/tokenRules/bg.png';
import TokenRedWhiteRules from './images/parts/tokenRules/rw.png';
import TokenGreenBlueRules from './images/parts/tokenRules/gu.png';

import LandOverlay from './images/overlay/C-overlay.png';
import InvocationPt from './images/pt/invocation/A.png';
import InventionPt from './images/pt/invention/inventionPT.png';
import PtA from './images/pt/regular/m15PTA.png';
import PtW from './images/pt/regular/m15PTW.png';
import PtU from './images/pt/regular/m15PTU.png';
import PtB from './images/pt/regular/m15PTB.png';
import PtR from './images/pt/regular/m15PTR.png';
import PtG from './images/pt/regular/m15PTM.png';
import PtM from './images/pt/regular/m15PTM.png';
import PtC from './images/pt/regular/m15PTC.png';
import PtV from './images/pt/regular/m15PTV.png';
import PtANickname from './images/pt/nickname/m15NicknamePTA.png';
import PtWNickname from './images/pt/nickname/m15NicknamePTW.png';
import PtUNickname from './images/pt/nickname/m15NicknamePTU.png';
import PtBNickname from './images/pt/nickname/m15NicknamePTB.png';
import PtRNickname from './images/pt/nickname/m15NicknamePTR.png';
import PtGNickname from './images/pt/nickname/m15NicknamePTM.png';
import PtMNickname from './images/pt/nickname/m15NicknamePTM.png';
import PtCNickname from './images/pt/nickname/m15NicknamePTC.png';
import PtABorderless from './images/pt/borderless/a.png';
import PtWBorderless from './images/pt/borderless/w.png';
import PtUBorderless from './images/pt/borderless/u.png';
import PtBBorderless from './images/pt/borderless/b.png';
import PtRBorderless from './images/pt/borderless/r.png';
import PtGBorderless from './images/pt/borderless/g.png';
import PtCBorderless from './images/pt/borderless/c.png';
import PtMBorderless from './images/pt/borderless/m.png';
import PtVBorderless from './images/pt/borderless/v.png';
import PtLBorderless from './images/pt/borderless/l.png';

import SymbolLandWhite from './images/symbols/land/W.png';
import SymbolLandBlue from './images/symbols/land/U.png';
import SymbolLandBlack from './images/symbols/land/B.png';
import SymbolLandRed from './images/symbols/land/R.png';
import SymbolLandGreen from './images/symbols/land/G.png';
import SymbolLandColorless from './images/symbols/land/C.png';

import MythicRareIcon from './images/rarity/mythic.png';
import RareIcon from './images/rarity/rare.png';
import UncommonIcon from './images/rarity/uncommon.png';
import CommonIcon from './images/rarity/common.png';

import {
  BasicLandArtStyles,
  BasicLandType,
  CardArtStyles,
  ColorType,
  RarityType,
} from '../../interfaces/enums';

// Regular planeswalker frames (used for cards with up to 3 ability lines).
import PlaneswalkerRegularWhite from './images/mainframes/planeswalker/regular/planeswalkerFrameW.png';
import PlaneswalkerRegularWhiteThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameWThumb.png';
import PlaneswalkerRegularBlue from './images/mainframes/planeswalker/regular/planeswalkerFrameU.png';
import PlaneswalkerRegularBlueThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameUThumb.png';
import PlaneswalkerRegularBlack from './images/mainframes/planeswalker/regular/planeswalkerFrameB.png';
import PlaneswalkerRegularBlackThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameBThumb.png';
import PlaneswalkerRegularRed from './images/mainframes/planeswalker/regular/planeswalkerFrameR.png';
import PlaneswalkerRegularRedThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameRThumb.png';
import PlaneswalkerRegularGreen from './images/mainframes/planeswalker/regular/planeswalkerFrameG.png';
import PlaneswalkerRegularGreenThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameGThumb.png';
import PlaneswalkerRegularGold from './images/mainframes/planeswalker/regular/planeswalkerFrameM.png';
import PlaneswalkerRegularGoldThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameMThumb.png';
import PlaneswalkerRegularColorless from './images/mainframes/planeswalker/regular/planeswalkerFrameA.png';
import PlaneswalkerRegularColorlessThumb from './images/mainframes/planeswalker/regular/planeswalkerFrameAThumb.png';

// Tall planeswalker frames (used for cards with 4 or more ability lines).
import PlaneswalkerTallWhite from './images/mainframes/planeswalker/tall/planeswalkerTallW.png';
import PlaneswalkerTallWhiteThumb from './images/mainframes/planeswalker/tall/planeswalkerTallWThumb.png';
import PlaneswalkerTallBlue from './images/mainframes/planeswalker/tall/planeswalkerTallU.png';
import PlaneswalkerTallBlueThumb from './images/mainframes/planeswalker/tall/planeswalkerTallUThumb.png';
import PlaneswalkerTallBlack from './images/mainframes/planeswalker/tall/planeswalkerTallB.png';
import PlaneswalkerTallBlackThumb from './images/mainframes/planeswalker/tall/planeswalkerTallBThumb.png';
import PlaneswalkerTallRed from './images/mainframes/planeswalker/tall/planeswalkerTallR.png';
import PlaneswalkerTallRedThumb from './images/mainframes/planeswalker/tall/planeswalkerTallRThumb.png';
import PlaneswalkerTallGreen from './images/mainframes/planeswalker/tall/planeswalkerTallG.png';
import PlaneswalkerTallGreenThumb from './images/mainframes/planeswalker/tall/planeswalkerTallGThumb.png';
import PlaneswalkerTallGold from './images/mainframes/planeswalker/tall/planeswalkerTallM.png';
import PlaneswalkerTallGoldThumb from './images/mainframes/planeswalker/tall/planeswalkerTallMThumb.png';
import PlaneswalkerTallColorless from './images/mainframes/planeswalker/tall/planeswalkerTallA.png';
import PlaneswalkerTallColorlessThumb from './images/mainframes/planeswalker/tall/planeswalkerTallAThumb.png';

// Borderless planeswalker frames (Borderless art style, up to 3 ability lines).
import PlaneswalkerBorderlessWhite from './images/mainframes/planeswalker/borderless/w.png';
import PlaneswalkerBorderlessWhiteThumb from './images/mainframes/planeswalker/borderless/wThumb.png';
import PlaneswalkerBorderlessBlue from './images/mainframes/planeswalker/borderless/u.png';
import PlaneswalkerBorderlessBlueThumb from './images/mainframes/planeswalker/borderless/uThumb.png';
import PlaneswalkerBorderlessBlack from './images/mainframes/planeswalker/borderless/b.png';
import PlaneswalkerBorderlessBlackThumb from './images/mainframes/planeswalker/borderless/bThumb.png';
import PlaneswalkerBorderlessRed from './images/mainframes/planeswalker/borderless/r.png';
import PlaneswalkerBorderlessRedThumb from './images/mainframes/planeswalker/borderless/rThumb.png';
import PlaneswalkerBorderlessGreen from './images/mainframes/planeswalker/borderless/g.png';
import PlaneswalkerBorderlessGreenThumb from './images/mainframes/planeswalker/borderless/gThumb.png';
import PlaneswalkerBorderlessGold from './images/mainframes/planeswalker/borderless/m.png';
import PlaneswalkerBorderlessGoldThumb from './images/mainframes/planeswalker/borderless/mThumb.png';
import PlaneswalkerBorderlessColorless from './images/mainframes/planeswalker/borderless/a.png';
import PlaneswalkerBorderlessColorlessThumb from './images/mainframes/planeswalker/borderless/aThumb.png';

// Tall borderless planeswalker frames (Borderless art style, 4+ ability lines).
import PlaneswalkerTallBorderlessWhite from './images/mainframes/planeswalker/tallBorderless/w.png';
import PlaneswalkerTallBorderlessWhiteThumb from './images/mainframes/planeswalker/tallBorderless/wThumb.png';
import PlaneswalkerTallBorderlessBlue from './images/mainframes/planeswalker/tallBorderless/u.png';
import PlaneswalkerTallBorderlessBlueThumb from './images/mainframes/planeswalker/tallBorderless/uThumb.png';
import PlaneswalkerTallBorderlessBlack from './images/mainframes/planeswalker/tallBorderless/b.png';
import PlaneswalkerTallBorderlessBlackThumb from './images/mainframes/planeswalker/tallBorderless/bThumb.png';
import PlaneswalkerTallBorderlessRed from './images/mainframes/planeswalker/tallBorderless/r.png';
import PlaneswalkerTallBorderlessRedThumb from './images/mainframes/planeswalker/tallBorderless/rThumb.png';
import PlaneswalkerTallBorderlessGreen from './images/mainframes/planeswalker/tallBorderless/g.png';
import PlaneswalkerTallBorderlessGreenThumb from './images/mainframes/planeswalker/tallBorderless/gThumb.png';
import PlaneswalkerTallBorderlessGold from './images/mainframes/planeswalker/tallBorderless/m.png';
import PlaneswalkerTallBorderlessGoldThumb from './images/mainframes/planeswalker/tallBorderless/mThumb.png';
import PlaneswalkerTallBorderlessColorless from './images/mainframes/planeswalker/tallBorderless/a.png';
import PlaneswalkerTallBorderlessColorlessThumb from './images/mainframes/planeswalker/tallBorderless/aThumb.png';

import PlaneswalkerPt from './images/pt/planeswalker/LoyaltyBegin.png';

// Ability-line dividers and rules-area masks for the banded text background.
import PlaneswalkerAbilityLineOdd from './images/mainframes/planeswalker/abilityLineOdd.png';
import PlaneswalkerAbilityLineEven from './images/mainframes/planeswalker/abilityLineEven.png';
import PlaneswalkerRulesMask from './images/mainframes/planeswalker/regular/planeswalkerMaskRules.png';
import PlaneswalkerTallRulesMask from './images/mainframes/planeswalker/tall/planeswalkerTallMaskRules.png';

import LoyaltyUp from './images/symbols/loyalty/LoyaltyUp.png';
import LoyaltyDown from './images/symbols/loyalty/LoyaltyDown.png';
import LoyaltyNeutral from './images/symbols/loyalty/LoyaltyNeutral.png';

import NicknameTitleA from './images/nickname/m15NicknameTitleA.png';
import NicknameTitleW from './images/nickname/m15NicknameTitleW.png';
import NicknameTitleU from './images/nickname/m15NicknameTitleU.png';
import NicknameTitleB from './images/nickname/m15NicknameTitleB.png';
import NicknameTitleR from './images/nickname/m15NicknameTitleR.png';
import NicknameTitleG from './images/nickname/m15NicknameTitleG.png';
import NicknameTitleM from './images/nickname/m15NicknameTitleM.png';
import NicknameTitleL from './images/nickname/m15NicknameTitleL.png';
import NicknameTitleWhiteBlue from './images/nickname/m15NicknameTitleWU.png';
import NicknameTitleBlueBlack from './images/nickname/m15NicknameTitleUB.png';
import NicknameTitleBlackRed from './images/nickname/m15NicknameTitleBR.png';
import NicknameTitleRedGreen from './images/nickname/m15NicknameTitleRG.png';
import NicknameTitleGreenWhite from './images/nickname/m15NicknameTitleGW.png';
import NicknameTitleWhiteBlack from './images/nickname/m15NicknameTitleWB.png';
import NicknameTitleBlueRed from './images/nickname/m15NicknameTitleUR.png';
import NicknameTitleBlackGreen from './images/nickname/m15NicknameTitleBG.png';
import NicknameTitleRedWhite from './images/nickname/m15NicknameTitleRW.png';
import NicknameTitleGreenBlue from './images/nickname/m15NicknameTitleGU.png';

// Nickname pinlines for the planeswalker card title region: single colors and
// the blended two-color combos produced by scripts/generate-parts.cjs.
import PlaneswalkerNicknamePlateA from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameA.png';
import PlaneswalkerNicknamePlateW from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameW.png';
import PlaneswalkerNicknamePlateU from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameU.png';
import PlaneswalkerNicknamePlateB from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameB.png';
import PlaneswalkerNicknamePlateR from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameR.png';
import PlaneswalkerNicknamePlateG from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameG.png';
import PlaneswalkerNicknamePlateM from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameM.png';
import PlaneswalkerNicknamePlateWhiteBlue from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameWU.png';
import PlaneswalkerNicknamePlateBlueBlack from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameUB.png';
import PlaneswalkerNicknamePlateBlackRed from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameBR.png';
import PlaneswalkerNicknamePlateRedGreen from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameRG.png';
import PlaneswalkerNicknamePlateGreenWhite from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameGW.png';
import PlaneswalkerNicknamePlateWhiteBlack from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameWB.png';
import PlaneswalkerNicknamePlateBlueRed from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameUR.png';
import PlaneswalkerNicknamePlateBlackGreen from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameBG.png';
import PlaneswalkerNicknamePlateRedWhite from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameRW.png';
import PlaneswalkerNicknamePlateGreenBlue from './images/mainframes/planeswalker/nickname/planeswalkerNicknameFrameGU.png';

export interface ImageResData {
  highRes: string;
  lowRes?: string;
}

// export const getFallbackCover = () => NoCover;
export const getFallbackCover = () => 'https://picsum.photos/700/600';

export const getPt = (
  color: ColorType,
  isArtefact = false,
  isVehicle = false,
  isNickname = false,
  isBorderless = false,
  isLand = false,
) => {
  if (isLand) {
    return PtLBorderless;
  }
  if (isArtefact) {
    if (color === ColorType.Gold) {
      if (isBorderless) {
        return isVehicle ? PtVBorderless : PtMBorderless;
      }
      return isNickname ? PtMNickname : PtM;
    }
    if (isBorderless) {
      return isVehicle ? PtVBorderless : PtABorderless;
    }
    if (isNickname) {
      return isVehicle ? PtV : PtANickname;
    }
    return isVehicle ? PtV : PtA;
  }

  switch (color) {
    case ColorType.White:
      if (isBorderless) {
        return PtWBorderless;
      }
      return isNickname ? PtWNickname : PtW;
    case ColorType.Blue:
      if (isBorderless) {
        return PtUBorderless;
      }
      return isNickname ? PtUNickname : PtU;
    case ColorType.Black:
      if (isBorderless) {
        return PtBBorderless;
      }
      return isNickname ? PtBNickname : PtB;
    case ColorType.Red:
      if (isBorderless) {
        return PtRBorderless;
      }
      return isNickname ? PtRNickname : PtR;
    case ColorType.Green:
      if (isBorderless) {
        return PtGBorderless;
      }
      return isNickname ? PtGNickname : PtG;
    case ColorType.Gold:
      if (isBorderless) {
        return PtMBorderless;
      }
      return isNickname ? PtMNickname : PtM;
    default:
      if (isBorderless) {
        return PtCBorderless;
      }
      return isNickname ? PtCNickname : PtC;
  }
};

// Two-color nickname title plates, keyed by the combo variant.
const NICKNAME_TITLE_COMBOS: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: NicknameTitleWhiteBlue,
  ub: NicknameTitleBlueBlack,
  br: NicknameTitleBlackRed,
  rg: NicknameTitleRedGreen,
  gw: NicknameTitleGreenWhite,
  wb: NicknameTitleWhiteBlack,
  ur: NicknameTitleBlueRed,
  bg: NicknameTitleBlackGreen,
  rw: NicknameTitleRedWhite,
  gu: NicknameTitleGreenBlue,
};

// On two-color cards the blended combo plate replaces the regular gold ('m')
// plate. Pass the card's colors (card-text identity for lands).
export const getNicknameTitle = (
  color: ColorType,
  isArtefact = false,
  isLand = false,
  colors?: ColorType[],
) => {
  if (isLand && color === ColorType.Colorless) {
    return NicknameTitleL;
  }
  // Two-color cards (including two-color artifacts) use the blended combo plate
  // rather than the gold or artefact plate.
  if (colors && colors.length === 2) {
    return NICKNAME_TITLE_COMBOS[getTwoColorVariant(colors)];
  }
  if (isArtefact) {
    return NicknameTitleA;
  }

  switch (color) {
    case ColorType.White:
      return NicknameTitleW;
    case ColorType.Blue:
      return NicknameTitleU;
    case ColorType.Black:
      return NicknameTitleB;
    case ColorType.Red:
      return NicknameTitleR;
    case ColorType.Green:
      return NicknameTitleG;
    case ColorType.Gold:
      return NicknameTitleM;
    default:
      return NicknameTitleA;
  }
};

export const getColorMainframe = (
  color: ColorType,
  isEnchantment = false,
  isArtifact = false,
  isVehicle = false,
): ImageResData | string => {
  // A colorless artifact uses the artefact frame instead of the plain colorless frame.
  if (isArtifact) {
    if (isEnchantment) {
      return { highRes: ArtefactNyxMainframe, lowRes: LowResArtefactMainframeNyx };
    }
    return isVehicle
      ? { highRes: VehicleMainframe, lowRes: LowResVehicleMainframe }
      : {
          highRes: ArtefactMainframe,
          lowRes: LowResArtefactMainframe,
        };
  }
  switch (color) {
    case ColorType.White:
      return isEnchantment
        ? {
            highRes: WhiteNyxMainframe,
            lowRes: LowResWhiteMainframeNyx,
          }
        : { highRes: WhiteMainframe, lowRes: LowResWhiteMainframe };
    case ColorType.Blue:
      return isEnchantment
        ? {
            highRes: BlueNyxMainframe,
            lowRes: LowResBlueMainframeNyx,
          }
        : { highRes: BlueMainframe, lowRes: LowResBlueMainframe };
    case ColorType.Black:
      return isEnchantment
        ? {
            highRes: BlackNyxMainframe,
            lowRes: LowResBlackMainframeNyx,
          }
        : { highRes: BlackMainframe, lowRes: LowResBlackMainframe };
    case ColorType.Red:
      return isEnchantment
        ? { highRes: RedNyxMainframe, lowRes: LowResRedMainframeNyx }
        : {
            highRes: RedMainframe,
            lowRes: LowResRedMainframe,
          };
    case ColorType.Green:
      return isEnchantment
        ? {
            highRes: GreenNyxMainframe,
            lowRes: LowResGreenMainframeNyx,
          }
        : { highRes: GreenMainframe, lowRes: LowResGreenMainframe };
    case ColorType.Gold:
      return isEnchantment
        ? {
            highRes: GoldNyxMainframe,
            lowRes: LowResGoldMainframeNyx,
          }
        : { highRes: GoldMainframe, lowRes: LowResGoldMainframe };
    default:
      return isEnchantment
        ? {
            highRes: ColorlessNyxMainframe,
            lowRes: LowResColorlessMainframeNyx,
          }
        : { highRes: ColorlessMainframe, lowRes: LowResColorlessMainframe };
  }
};

export const getBorderlessMainframe = (
  color: ColorType,
  isLand = false,
  isArtifact = false,
  isNickname = false,
): ImageResData => {
  // The borderless nickname frames have no thumb variants, so only the base
  // showcase frames carry a low-res asset.
  if (isArtifact) {
    return isNickname
      ? { highRes: BorderlessNicknameFrameA }
      : { highRes: BorderlessFrameA, lowRes: BorderlessFrameALowRes };
  }
  if (isLand && color === ColorType.Colorless) {
    return isNickname
      ? { highRes: BorderlessNicknameFrameL }
      : { highRes: BorderlessFrameL, lowRes: BorderlessFrameLLowRes };
  }

  switch (color) {
    case ColorType.White:
      return isNickname
        ? { highRes: BorderlessNicknameFrameW }
        : { highRes: BorderlessFrameW, lowRes: BorderlessFrameWLowRes };
    case ColorType.Blue:
      return isNickname
        ? { highRes: BorderlessNicknameFrameU }
        : { highRes: BorderlessFrameU, lowRes: BorderlessFrameULowRes };
    case ColorType.Black:
      return isNickname
        ? { highRes: BorderlessNicknameFrameB }
        : { highRes: BorderlessFrameB, lowRes: BorderlessFrameBLowRes };
    case ColorType.Red:
      return isNickname
        ? { highRes: BorderlessNicknameFrameR }
        : { highRes: BorderlessFrameR, lowRes: BorderlessFrameRLowRes };
    case ColorType.Green:
      return isNickname
        ? { highRes: BorderlessNicknameFrameG }
        : { highRes: BorderlessFrameG, lowRes: BorderlessFrameGLowRes };
    case ColorType.Gold:
      return isNickname
        ? { highRes: BorderlessNicknameFrameM }
        : { highRes: BorderlessFrameM, lowRes: BorderlessFrameMLowRes };
    default:
      return isNickname
        ? { highRes: BorderlessNicknameFrameC }
        : { highRes: BorderlessFrameC, lowRes: BorderlessFrameCLowRes };
  }
};

export const getExtendedMainframe = (
  color: ColorType,
  isLand = false,
  isArtifact = false,
  isVehicle = false,
  isEnchantment = false,
): ImageResData => {
  if (isArtifact) {
    if (isVehicle) return { highRes: ExtendedFrameV, lowRes: ExtendedFrameVLowRes };
    return isEnchantment
      ? { highRes: ExtendedFrameANyx, lowRes: ExtendedFrameANyxLowRes }
      : { highRes: ExtendedFrameA, lowRes: ExtendedFrameALowRes };
  }
  switch (color) {
    case ColorType.White:
      if (isEnchantment) return { highRes: ExtendedFrameWNyx, lowRes: ExtendedFrameWNyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameWL, lowRes: ExtendedFrameWLLowRes }
        : { highRes: ExtendedFrameW, lowRes: ExtendedFrameWLowRes };
    case ColorType.Blue:
      if (isEnchantment) return { highRes: ExtendedFrameUNyx, lowRes: ExtendedFrameUNyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameUL, lowRes: ExtendedFrameULLowRes }
        : { highRes: ExtendedFrameU, lowRes: ExtendedFrameULowRes };
    case ColorType.Black:
      if (isEnchantment) return { highRes: ExtendedFrameBNyx, lowRes: ExtendedFrameBNyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameBL, lowRes: ExtendedFrameBLLowRes }
        : { highRes: ExtendedFrameB, lowRes: ExtendedFrameBLowRes };
    case ColorType.Red:
      if (isEnchantment) return { highRes: ExtendedFrameRNyx, lowRes: ExtendedFrameRNyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameRL, lowRes: ExtendedFrameRLLowRes }
        : { highRes: ExtendedFrameR, lowRes: ExtendedFrameRLowRes };
    case ColorType.Green:
      if (isEnchantment) return { highRes: ExtendedFrameGNyx, lowRes: ExtendedFrameGNyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameGL, lowRes: ExtendedFrameGLLowRes }
        : { highRes: ExtendedFrameG, lowRes: ExtendedFrameGLowRes };
    case ColorType.Gold:
      if (isEnchantment) return { highRes: ExtendedFrameMNyx, lowRes: ExtendedFrameMNyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameML, lowRes: ExtendedFrameMLLowRes }
        : { highRes: ExtendedFrameM, lowRes: ExtendedFrameMLowRes };
    default:
      if (isEnchantment) return { highRes: ExtendedFrameANyx, lowRes: ExtendedFrameANyxLowRes };
      return isLand
        ? { highRes: ExtendedFrameL, lowRes: ExtendedFrameLLowRes }
        : { highRes: ExtendedFrameC, lowRes: ExtendedFrameCLowRes };
  }
};

export const getBlack = () => {
  return Black;
};

export const getInnerCrown = (color: ColorType, isArtefact = false) => {
  if (isArtefact) {
    return InnerCrownArtefact;
  }

  switch (color) {
    case ColorType.White:
      return InnerCrownWhite;
    case ColorType.Blue:
      return InnerCrownBlue;
    case ColorType.Black:
      return InnerCrownBlack;
    case ColorType.Red:
      return InnerCrownRed;
    case ColorType.Green:
      return InnerCrownGreen;
    case ColorType.Gold:
      return InnerCrownGold;
    default:
      return InnerCrownArtefact;
  }
};

export const getCrownFloatingExtendedArtFix = () => CrownFloatingExtendedArtFix;

// Keys for the two-color crown combos, in WUBRG wheel order. These match the
// combo variant keys returned by getTwoColorVariant for a two-color card.
type CrownComboKey = 'wu' | 'ub' | 'br' | 'rg' | 'gw' | 'wb' | 'ur' | 'bg' | 'rw' | 'gu';

const CROWN_COMBOS: Record<CrownComboKey, ImageResData> = {
  wu: { highRes: CrownWu, lowRes: CrownWuLowRes },
  ub: { highRes: CrownUb, lowRes: CrownUbLowRes },
  br: { highRes: CrownBr, lowRes: CrownBrLowRes },
  rg: { highRes: CrownRg, lowRes: CrownRgLowRes },
  gw: { highRes: CrownGw, lowRes: CrownGwLowRes },
  wb: { highRes: CrownWb, lowRes: CrownWbLowRes },
  ur: { highRes: CrownUr, lowRes: CrownUrLowRes },
  bg: { highRes: CrownBg, lowRes: CrownBgLowRes },
  rw: { highRes: CrownRw, lowRes: CrownRwLowRes },
  gu: { highRes: CrownGu, lowRes: CrownGuLowRes },
};

const CROWN_FLOATING_COMBOS: Record<CrownComboKey, ImageResData> = {
  wu: { highRes: CrownWuFloating, lowRes: CrownWuFloatingLowRes },
  ub: { highRes: CrownUbFloating, lowRes: CrownUbFloatingLowRes },
  br: { highRes: CrownBrFloating, lowRes: CrownBrFloatingLowRes },
  rg: { highRes: CrownRgFloating, lowRes: CrownRgFloatingLowRes },
  gw: { highRes: CrownGwFloating, lowRes: CrownGwFloatingLowRes },
  wb: { highRes: CrownWbFloating, lowRes: CrownWbFloatingLowRes },
  ur: { highRes: CrownUrFloating, lowRes: CrownUrFloatingLowRes },
  bg: { highRes: CrownBgFloating, lowRes: CrownBgFloatingLowRes },
  rw: { highRes: CrownRwFloating, lowRes: CrownRwFloatingLowRes },
  gu: { highRes: CrownGuFloating, lowRes: CrownGuFloatingLowRes },
};

const CROWN_NICKNAME_COMBOS: Record<CrownComboKey, ImageResData> = {
  wu: { highRes: CrownWuNickname, lowRes: CrownWuNicknameLowRes },
  ub: { highRes: CrownUbNickname, lowRes: CrownUbNicknameLowRes },
  br: { highRes: CrownBrNickname, lowRes: CrownBrNicknameLowRes },
  rg: { highRes: CrownRgNickname, lowRes: CrownRgNicknameLowRes },
  gw: { highRes: CrownGwNickname, lowRes: CrownGwNicknameLowRes },
  wb: { highRes: CrownWbNickname, lowRes: CrownWbNicknameLowRes },
  ur: { highRes: CrownUrNickname, lowRes: CrownUrNicknameLowRes },
  bg: { highRes: CrownBgNickname, lowRes: CrownBgNicknameLowRes },
  rw: { highRes: CrownRwNickname, lowRes: CrownRwNicknameLowRes },
  gu: { highRes: CrownGuNickname, lowRes: CrownGuNicknameLowRes },
};

// Selects the two-color combo crown for an (unordered) color pair, picking the
// style that matches the per-color crown selection: nickname first, then
// floating (full-art), otherwise the base crown.
const getTwoColorCrown = (
  colors: ColorType[],
  isFullart: boolean,
  isNickname: boolean,
): ImageResData => {
  const variant = getTwoColorVariant(colors) as CrownComboKey;
  if (isNickname) return CROWN_NICKNAME_COMBOS[variant];
  if (isFullart) return CROWN_FLOATING_COMBOS[variant];
  return CROWN_COMBOS[variant];
};

export const getCrown = (
  color: ColorType,
  isFullart = false,
  isLand = false,
  isArtefact = false,
  isNickname = false,
  colors: ColorType[] = [],
): ImageResData | string => {
  if (isLand && color === ColorType.Colorless) {
    if (isNickname) return { highRes: CrownLandNickname, lowRes: CrownLandNicknameLowRes };
    return isFullart
      ? { highRes: CrownLandFloating, lowRes: CrownLandFloatingLowRes }
      : { highRes: CrownLand, lowRes: CrownLandLowRes };
  }
  // Non-land cards with exactly two colors use the two-color combo crown,
  // including two-color artifacts, rather than the artefact or gold crown.
  if (colors.length === 2) {
    return getTwoColorCrown(colors, isFullart, isNickname);
  }

  if (isArtefact) {
    if (isNickname) return { highRes: CrownArtefactNickname, lowRes: CrownArtefactNicknameLowRes };
    return isFullart
      ? { highRes: CrownArtefactFloating, lowRes: CrownArtefactFloatingLowRes }
      : { highRes: CrownArtefact, lowRes: CrownArtefactLowRes };
  }

  switch (color) {
    case ColorType.White:
      if (isNickname) return { highRes: CrownWhiteNickname, lowRes: CrownWhiteNicknameLowRes };
      return isFullart
        ? { highRes: CrownWhiteFloating, lowRes: CrownWhiteFloatingLowRes }
        : { highRes: CrownWhite, lowRes: CrownWhiteLowRes };
    case ColorType.Blue:
      if (isNickname) return { highRes: CrownBlueNickname, lowRes: CrownBlueNicknameLowRes };
      return isFullart
        ? { highRes: CrownBlueFloating, lowRes: CrownBlueFloatingLowRes }
        : { highRes: CrownBlue, lowRes: CrownBlueLowRes };
    case ColorType.Black:
      if (isNickname) return { highRes: CrownBlackNickname, lowRes: CrownBlackNicknameLowRes };
      return isFullart
        ? { highRes: CrownBlackFloating, lowRes: CrownBlackFloatingLowRes }
        : { highRes: CrownBlack, lowRes: CrownBlackLowRes };
    case ColorType.Red:
      if (isNickname) return { highRes: CrownRedNickname, lowRes: CrownRedNicknameLowRes };
      return isFullart
        ? { highRes: CrownRedFloating, lowRes: CrownRedFloatingLowRes }
        : { highRes: CrownRed, lowRes: CrownRedLowRes };
    case ColorType.Green:
      if (isNickname) return { highRes: CrownGreenNickname, lowRes: CrownGreenNicknameLowRes };
      return isFullart
        ? { highRes: CrownGreenFloating, lowRes: CrownGreenFloatingLowRes }
        : { highRes: CrownGreen, lowRes: CrownGreenLowRes };
    case ColorType.Gold:
      if (isNickname) return { highRes: CrownGoldNickname, lowRes: CrownGoldNicknameLowRes };
      return isFullart
        ? { highRes: CrownGoldFloating, lowRes: CrownGoldFloatingLowRes }
        : { highRes: CrownGold, lowRes: CrownGoldLowRes };
    default:
      if (isNickname)
        return { highRes: CrownColorlessNickname, lowRes: CrownColorlessNicknameLowRes };
      return isFullart
        ? { highRes: CrownColorlessFloating, lowRes: CrownColorlessFloatingLowRes }
        : { highRes: CrownColorless, lowRes: CrownColorlessLowRes };
  }
};

const TokenArtefactFrame = {
  highRes: TokenArtefactMainframe,
  lowRes: TokenArtefactMainframeLowRes,
};
const TokenColorlessFrame = {
  highRes: TokenColorlessMainframe,
  lowRes: TokenColorlessMainframeLowRes,
};
const TokenWhiteFrame = { highRes: TokenWhiteMainframe, lowRes: TokenWhiteMainframeLowRes };
const TokenBlueFrame = { highRes: TokenBlueMainframe, lowRes: TokenBlueMainframeLowRes };
const TokenBlackFrame = { highRes: TokenBlackMainframe, lowRes: TokenBlackMainframeLowRes };
const TokenRedFrame = { highRes: TokenRedMainframe, lowRes: TokenRedMainframeLowRes };
const TokenGreenFrame = { highRes: TokenGreenMainframe, lowRes: TokenGreenMainframeLowRes };
const TokenGoldFrame = { highRes: TokenGoldMainframe, lowRes: TokenGoldMainframeLowRes };
const TokenLandFrame = { highRes: TokenLandMainframe, lowRes: TokenLandMainframeLowRes };

export const getTokenMainframe = (color: ColorType, isArtifact = false, isLand = false) => {
  if (isArtifact && color === ColorType.Colorless) return TokenArtefactFrame;
  if (isLand && color === ColorType.Colorless) return TokenLandFrame;
  switch (color) {
    case ColorType.White:
      return TokenWhiteFrame;
    case ColorType.Blue:
      return TokenBlueFrame;
    case ColorType.Black:
      return TokenBlackFrame;
    case ColorType.Red:
      return TokenRedFrame;
    case ColorType.Green:
      return TokenGreenFrame;
    case ColorType.Gold:
      return TokenGoldFrame;
    default:
      return TokenColorlessFrame;
  }
};

export const getLoyaltyIcon = (loyaltyAction?: string) => {
  if (!loyaltyAction) return '';
  if (loyaltyAction.indexOf('+') !== -1) return LoyaltyUp;
  if (loyaltyAction.indexOf('-') !== -1) return LoyaltyDown;
  if (loyaltyAction === '0') return LoyaltyNeutral;
  return '';
};

export const getPlaneswalkerPt = () => PlaneswalkerPt;

// Each entry pairs the full-resolution frame with its low-res thumbnail, used
// by ImageLoader for the blur-up placeholder while the full frame loads.
const planeswalkerFrames: Record<
  'regular' | 'tall' | 'borderless' | 'tallBorderless',
  Record<ColorType, ImageResData>
> = {
  regular: {
    [ColorType.White]: { highRes: PlaneswalkerRegularWhite, lowRes: PlaneswalkerRegularWhiteThumb },
    [ColorType.Blue]: { highRes: PlaneswalkerRegularBlue, lowRes: PlaneswalkerRegularBlueThumb },
    [ColorType.Black]: { highRes: PlaneswalkerRegularBlack, lowRes: PlaneswalkerRegularBlackThumb },
    [ColorType.Red]: { highRes: PlaneswalkerRegularRed, lowRes: PlaneswalkerRegularRedThumb },
    [ColorType.Green]: { highRes: PlaneswalkerRegularGreen, lowRes: PlaneswalkerRegularGreenThumb },
    [ColorType.Gold]: { highRes: PlaneswalkerRegularGold, lowRes: PlaneswalkerRegularGoldThumb },
    [ColorType.Colorless]: {
      highRes: PlaneswalkerRegularColorless,
      lowRes: PlaneswalkerRegularColorlessThumb,
    },
  },
  tall: {
    [ColorType.White]: { highRes: PlaneswalkerTallWhite, lowRes: PlaneswalkerTallWhiteThumb },
    [ColorType.Blue]: { highRes: PlaneswalkerTallBlue, lowRes: PlaneswalkerTallBlueThumb },
    [ColorType.Black]: { highRes: PlaneswalkerTallBlack, lowRes: PlaneswalkerTallBlackThumb },
    [ColorType.Red]: { highRes: PlaneswalkerTallRed, lowRes: PlaneswalkerTallRedThumb },
    [ColorType.Green]: { highRes: PlaneswalkerTallGreen, lowRes: PlaneswalkerTallGreenThumb },
    [ColorType.Gold]: { highRes: PlaneswalkerTallGold, lowRes: PlaneswalkerTallGoldThumb },
    [ColorType.Colorless]: {
      highRes: PlaneswalkerTallColorless,
      lowRes: PlaneswalkerTallColorlessThumb,
    },
  },
  borderless: {
    [ColorType.White]: {
      highRes: PlaneswalkerBorderlessWhite,
      lowRes: PlaneswalkerBorderlessWhiteThumb,
    },
    [ColorType.Blue]: {
      highRes: PlaneswalkerBorderlessBlue,
      lowRes: PlaneswalkerBorderlessBlueThumb,
    },
    [ColorType.Black]: {
      highRes: PlaneswalkerBorderlessBlack,
      lowRes: PlaneswalkerBorderlessBlackThumb,
    },
    [ColorType.Red]: { highRes: PlaneswalkerBorderlessRed, lowRes: PlaneswalkerBorderlessRedThumb },
    [ColorType.Green]: {
      highRes: PlaneswalkerBorderlessGreen,
      lowRes: PlaneswalkerBorderlessGreenThumb,
    },
    [ColorType.Gold]: {
      highRes: PlaneswalkerBorderlessGold,
      lowRes: PlaneswalkerBorderlessGoldThumb,
    },
    [ColorType.Colorless]: {
      highRes: PlaneswalkerBorderlessColorless,
      lowRes: PlaneswalkerBorderlessColorlessThumb,
    },
  },
  tallBorderless: {
    [ColorType.White]: {
      highRes: PlaneswalkerTallBorderlessWhite,
      lowRes: PlaneswalkerTallBorderlessWhiteThumb,
    },
    [ColorType.Blue]: {
      highRes: PlaneswalkerTallBorderlessBlue,
      lowRes: PlaneswalkerTallBorderlessBlueThumb,
    },
    [ColorType.Black]: {
      highRes: PlaneswalkerTallBorderlessBlack,
      lowRes: PlaneswalkerTallBorderlessBlackThumb,
    },
    [ColorType.Red]: {
      highRes: PlaneswalkerTallBorderlessRed,
      lowRes: PlaneswalkerTallBorderlessRedThumb,
    },
    [ColorType.Green]: {
      highRes: PlaneswalkerTallBorderlessGreen,
      lowRes: PlaneswalkerTallBorderlessGreenThumb,
    },
    [ColorType.Gold]: {
      highRes: PlaneswalkerTallBorderlessGold,
      lowRes: PlaneswalkerTallBorderlessGoldThumb,
    },
    [ColorType.Colorless]: {
      highRes: PlaneswalkerTallBorderlessColorless,
      lowRes: PlaneswalkerTallBorderlessColorlessThumb,
    },
  },
};

export const getPlaneswalkerMainframe = (
  color: ColorType,
  isTall = false,
  isBorderless = false,
): ImageResData => {
  let variant: 'regular' | 'tall' | 'borderless' | 'tallBorderless';
  if (isBorderless) variant = isTall ? 'tallBorderless' : 'borderless';
  else variant = isTall ? 'tall' : 'regular';

  return planeswalkerFrames[variant][color];
};

// Divider strips drawn between ability bands. `abilityLineOdd` transitions from
// the lighter band (top) to the darker band (bottom); `abilityLineEven` is the
// reverse. The band fill colors are the translucent edge rows of these strips.
export const getPlaneswalkerAbilityDivider = (odd: boolean) =>
  odd ? PlaneswalkerAbilityLineOdd : PlaneswalkerAbilityLineEven;

// Full-card (1500x2100) mask of the rules/text region, used to clip the banded
// background to the exact text-box shape (including the loyalty-plate notch).
export const getPlaneswalkerRulesMask = (isTall = false) =>
  isTall ? PlaneswalkerTallRulesMask : PlaneswalkerRulesMask;

export const getInvocationPt = () => InvocationPt;

export const getInventionPt = () => InventionPt;

export const getInventionMainframe = (color: ColorType, isArtifact = false) => {
  if (isArtifact && color === ColorType.Colorless) return InventionArtefactMainframe;
  switch (color) {
    case ColorType.White:
      return InventionWhiteMainframe;
    case ColorType.Blue:
      return InventionBlueMainframe;
    case ColorType.Black:
      return InventionBlackMainframe;
    case ColorType.Red:
      return InventionRedMainframe;
    case ColorType.Green:
      return InventionGreenMainframe;
    case ColorType.Gold:
      return InventionGoldMainframe;
    default:
      return InventionColorlessMainframe;
  }
};

export const getInvocationMainframe = (color: ColorType) => {
  switch (color) {
    case ColorType.White:
      return InvocationWhiteMainframe;
    case ColorType.Blue:
      return InvocationBlueMainframe;
    case ColorType.Black:
      return InvocationBlackMainframe;
    case ColorType.Red:
      return InvocationRedMainframe;
    case ColorType.Green:
      return InvocationGreenMainframe;
    default:
      return InvocationGoldMainframe;
  }
};

// Maps an unordered pair of colors to its two-color pinline asset. The combo
// files are named in WUBRG wheel order (wu, ub, br, rg, gw, wb, ur, bg, rw, gu),
// so we normalize here regardless of the order the colors arrive in.
const getTwoColorPinline = (colors: ColorType[]) => {
  if (colors.includes(ColorType.White)) {
    if (colors.includes(ColorType.Blue)) return WhiteBluePinline;
    if (colors.includes(ColorType.Black)) return WhiteBlackPinline;
  }
  if (colors.includes(ColorType.Blue)) {
    if (colors.includes(ColorType.Black)) return BlueBlackPinline;
    if (colors.includes(ColorType.Red)) return BlueRedPinline;
  }
  if (colors.includes(ColorType.Black)) {
    if (colors.includes(ColorType.Green)) return BlackGreenPinline;
    if (colors.includes(ColorType.Red)) return BlackRedPinline;
  }
  if (colors.includes(ColorType.Red)) {
    if (colors.includes(ColorType.Green)) return RedGreenPinline;
    if (colors.includes(ColorType.White)) return RedWhitePinline;
  }
  if (colors.includes(ColorType.Green)) {
    if (colors.includes(ColorType.Blue)) return GreenBluePinline;
    if (colors.includes(ColorType.White)) return GreenWhitePinline;
  }
  return GoldPinline;
};

const getSingleColorPinline = (color: ColorType) => {
  if (color === ColorType.White) return WhitePinline;
  if (color === ColorType.Blue) return BluePinline;
  if (color === ColorType.Black) return BlackPinline;
  if (color === ColorType.Red) return RedPinline;
  if (color === ColorType.Green) return GreenPinline;
  return GoldPinline;
};

// Pinlines render only on:
//  - artifacts that are not colorless (pinline matches the card's colors)
//  - non-artifact gold cards with exactly two colors (two-color combo pinline)
// Everything else returns '' (no pinline layer).
//
// For the extended and borderless art styles, only two-color combination
// pinlines were generated (from those styles' own frames); every other case
// gets no pinline instead of falling back to the regular m15-carved assets.
//
// Tokens behave the same way: only the two-color token pinlines exist, so a
// token with any other color count gets no pinline (the token frame is drawn
// whole instead).
export const getPinline = (
  colors: ColorType[],
  isArtifact: boolean,
  artStyle?: BasicLandArtStyles | CardArtStyles,
  isToken = false,
) => {
  if (isToken) {
    if (colors.length === 2) return TOKEN_PINLINES[getTwoColorVariant(colors)];
    return '';
  }

  const variantPinlines =
    artStyle === CardArtStyles.Extended
      ? EXTENDED_PINLINES
      : artStyle === CardArtStyles.Borderless
        ? BORDERLESS_PINLINES
        : null;

  if (variantPinlines) {
    if (colors.length === 2) return variantPinlines[getTwoColorVariant(colors)];
    return '';
  }

  if (isArtifact) {
    if (colors.length === 0) return '';
    if (colors.length === 1) return getSingleColorPinline(colors[0]);
    if (colors.length === 2) return getTwoColorPinline(colors);
    return GoldPinline;
  }

  if (colors.length === 2) return getTwoColorPinline(colors);

  return '';
};

// Variant key shared by the title / type / rules frame parts. '' means no part.
type PartVariant =
  | ''
  | 'w'
  | 'u'
  | 'b'
  | 'r'
  | 'g'
  | 'm'
  | 'wu'
  | 'ub'
  | 'br'
  | 'rg'
  | 'gw'
  | 'wb'
  | 'ur'
  | 'bg'
  | 'rw'
  | 'gu';

// Maps an unordered color pair to its combo variant key (WUBRG wheel order).
const getTwoColorVariant = (colors: ColorType[]): PartVariant => {
  if (colors.includes(ColorType.White)) {
    if (colors.includes(ColorType.Blue)) return 'wu';
    if (colors.includes(ColorType.Black)) return 'wb';
  }
  if (colors.includes(ColorType.Blue)) {
    if (colors.includes(ColorType.Black)) return 'ub';
    if (colors.includes(ColorType.Red)) return 'ur';
  }
  if (colors.includes(ColorType.Black)) {
    if (colors.includes(ColorType.Green)) return 'bg';
    if (colors.includes(ColorType.Red)) return 'br';
  }
  if (colors.includes(ColorType.Red)) {
    if (colors.includes(ColorType.Green)) return 'rg';
    if (colors.includes(ColorType.White)) return 'rw';
  }
  if (colors.includes(ColorType.Green)) {
    if (colors.includes(ColorType.Blue)) return 'gu';
    if (colors.includes(ColorType.White)) return 'gw';
  }
  return 'm';
};

const getSingleColorVariant = (color: ColorType): PartVariant => {
  if (color === ColorType.White) return 'w';
  if (color === ColorType.Blue) return 'u';
  if (color === ColorType.Black) return 'b';
  if (color === ColorType.Red) return 'r';
  if (color === ColorType.Green) return 'g';
  return 'm';
};

// Selection logic for the rules (text box) frame part:
//  - artifacts (non-colorless): part matches the card's colors
//      (single color, two-color combo, or gold for 3+)
//  - non-artifact cards with exactly two colors: golden ('m') part
//  - everything else: no part ('')
// Note this differs from the pinline for two-color non-artifacts, which the
// user wants rendered as the golden part rather than the two-color combo.
const getRulesVariant = (colors: ColorType[], isArtifact: boolean): PartVariant => {
  if (isArtifact) {
    if (colors.length === 0) return '';
    if (colors.length === 1) return getSingleColorVariant(colors[0]);
    if (colors.length === 2) return getTwoColorVariant(colors);
    return 'm';
  }

  if (colors.length === 2) return 'm';

  return '';
};

// Selection logic for the title and type frame parts. Unlike the rules part,
// these never use the two-color combo: any multicolor artifact (two-color or
// 3+) uses the golden ('m') part, as do two-color non-artifact cards.
const getTitleTypeVariant = (colors: ColorType[], isArtifact: boolean): PartVariant => {
  if (isArtifact) {
    if (colors.length === 0) return '';
    if (colors.length === 1) return getSingleColorVariant(colors[0]);
    return 'm';
  }

  if (colors.length === 2) return 'm';

  return '';
};

const TITLE_PARTS: Record<PartVariant, string> = {
  '': '',
  w: WhiteTitle,
  u: BlueTitle,
  b: BlackTitle,
  r: RedTitle,
  g: GreenTitle,
  m: GoldTitle,
  wu: WhiteBlueTitle,
  ub: BlueBlackTitle,
  br: BlackRedTitle,
  rg: RedGreenTitle,
  gw: GreenWhiteTitle,
  wb: WhiteBlackTitle,
  ur: BlueRedTitle,
  bg: BlackGreenTitle,
  rw: RedWhiteTitle,
  gu: GreenBlueTitle,
};

const TYPE_PARTS: Record<PartVariant, string> = {
  '': '',
  w: WhiteType,
  u: BlueType,
  b: BlackType,
  r: RedType,
  g: GreenType,
  m: GoldType,
  wu: WhiteBlueType,
  ub: BlueBlackType,
  br: BlackRedType,
  rg: RedGreenType,
  gw: GreenWhiteType,
  wb: WhiteBlackType,
  ur: BlueRedType,
  bg: BlackGreenType,
  rw: RedWhiteType,
  gu: GreenBlueType,
};

const RULES_PARTS: Record<PartVariant, string> = {
  '': '',
  w: WhiteRules,
  u: BlueRules,
  b: BlackRules,
  r: RedRules,
  g: GreenRules,
  m: GoldRules,
  wu: WhiteBlueRules,
  ub: BlueBlackRules,
  br: BlackRedRules,
  rg: RedGreenRules,
  gw: GreenWhiteRules,
  wb: WhiteBlackRules,
  ur: BlueRedRules,
  bg: BlackGreenRules,
  rw: RedWhiteRules,
  gu: GreenBlueRules,
};

// Pinline variants generated from the extended / borderless frames. Only the
// two-color combinations exist; non-combo keys map to ''.
const EXTENDED_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: ExtendedWhiteBluePinline,
  ub: ExtendedBlueBlackPinline,
  br: ExtendedBlackRedPinline,
  rg: ExtendedRedGreenPinline,
  gw: ExtendedGreenWhitePinline,
  wb: ExtendedWhiteBlackPinline,
  ur: ExtendedBlueRedPinline,
  bg: ExtendedBlackGreenPinline,
  rw: ExtendedRedWhitePinline,
  gu: ExtendedGreenBluePinline,
};

const BORDERLESS_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: BorderlessWhiteBluePinline,
  ub: BorderlessBlueBlackPinline,
  br: BorderlessBlackRedPinline,
  rg: BorderlessRedGreenPinline,
  gw: BorderlessGreenWhitePinline,
  wb: BorderlessWhiteBlackPinline,
  ur: BorderlessBlueRedPinline,
  bg: BorderlessBlackGreenPinline,
  rw: BorderlessRedWhitePinline,
  gu: BorderlessGreenBluePinline,
};

// Planeswalker pinlines, one map per frame style. Like the extended /
// borderless pinlines, only the two-color combinations exist; non-combo keys
// map to '' because single-color (and colorless / 3+ color) planeswalkers
// render the whole frame instead of carving a pinline out of it.
const PLANESWALKER_REGULAR_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: PwRegularWhiteBluePinline,
  ub: PwRegularBlueBlackPinline,
  br: PwRegularBlackRedPinline,
  rg: PwRegularRedGreenPinline,
  gw: PwRegularGreenWhitePinline,
  wb: PwRegularWhiteBlackPinline,
  ur: PwRegularBlueRedPinline,
  bg: PwRegularBlackGreenPinline,
  rw: PwRegularRedWhitePinline,
  gu: PwRegularGreenBluePinline,
};

const PLANESWALKER_TALL_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: PwTallWhiteBluePinline,
  ub: PwTallBlueBlackPinline,
  br: PwTallBlackRedPinline,
  rg: PwTallRedGreenPinline,
  gw: PwTallGreenWhitePinline,
  wb: PwTallWhiteBlackPinline,
  ur: PwTallBlueRedPinline,
  bg: PwTallBlackGreenPinline,
  rw: PwTallRedWhitePinline,
  gu: PwTallGreenBluePinline,
};

const PLANESWALKER_BORDERLESS_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: PwBorderlessWhiteBluePinline,
  ub: PwBorderlessBlueBlackPinline,
  br: PwBorderlessBlackRedPinline,
  rg: PwBorderlessRedGreenPinline,
  gw: PwBorderlessGreenWhitePinline,
  wb: PwBorderlessWhiteBlackPinline,
  ur: PwBorderlessBlueRedPinline,
  bg: PwBorderlessBlackGreenPinline,
  rw: PwBorderlessRedWhitePinline,
  gu: PwBorderlessGreenBluePinline,
};

const PLANESWALKER_TALL_BORDERLESS_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: PwTallBorderlessWhiteBluePinline,
  ub: PwTallBorderlessBlueBlackPinline,
  br: PwTallBorderlessBlackRedPinline,
  rg: PwTallBorderlessRedGreenPinline,
  gw: PwTallBorderlessGreenWhitePinline,
  wb: PwTallBorderlessWhiteBlackPinline,
  ur: PwTallBorderlessBlueRedPinline,
  bg: PwTallBorderlessBlackGreenPinline,
  rw: PwTallBorderlessRedWhitePinline,
  gu: PwTallBorderlessGreenBluePinline,
};

// Selects the two-color pinline overlay for a planeswalker frame. Mirrors the
// variant branch logic of getPlaneswalkerMainframe. Returns '' unless the card
// has exactly two colors (single-color / colorless / 3+ render no pinline).
export const getPlaneswalkerPinline = (
  colors: ColorType[],
  isTall = false,
  isBorderless = false,
): string => {
  if (colors.length !== 2) return '';

  let variantPinlines: Record<PartVariant, string>;
  if (isBorderless) {
    variantPinlines = isTall
      ? PLANESWALKER_TALL_BORDERLESS_PINLINES
      : PLANESWALKER_BORDERLESS_PINLINES;
  } else {
    variantPinlines = isTall ? PLANESWALKER_TALL_PINLINES : PLANESWALKER_REGULAR_PINLINES;
  }

  return variantPinlines[getTwoColorVariant(colors)];
};

// Two-color planeswalker nickname plates, keyed by the combo variant.
const PLANESWALKER_NICKNAME_COMBOS: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: PlaneswalkerNicknamePlateWhiteBlue,
  ub: PlaneswalkerNicknamePlateBlueBlack,
  br: PlaneswalkerNicknamePlateBlackRed,
  rg: PlaneswalkerNicknamePlateRedGreen,
  gw: PlaneswalkerNicknamePlateGreenWhite,
  wb: PlaneswalkerNicknamePlateWhiteBlack,
  ur: PlaneswalkerNicknamePlateBlueRed,
  bg: PlaneswalkerNicknamePlateBlackGreen,
  rw: PlaneswalkerNicknamePlateRedWhite,
  gu: PlaneswalkerNicknamePlateGreenBlue,
};

// Selects the nickname plate for a planeswalker with a nickname. Two-color
// cards use the blended combo plate, matching getNicknameTitle. Colorless (or
// artifact) planeswalkers use the 'a' plate, gold (3+ colors) the 'm' plate.
export const getPlaneswalkerNicknamePlate = (color: ColorType, colors?: ColorType[]): string => {
  if (colors && colors.length === 2) {
    return PLANESWALKER_NICKNAME_COMBOS[getTwoColorVariant(colors)];
  }

  switch (color) {
    case ColorType.White:
      return PlaneswalkerNicknamePlateW;
    case ColorType.Blue:
      return PlaneswalkerNicknamePlateU;
    case ColorType.Black:
      return PlaneswalkerNicknamePlateB;
    case ColorType.Red:
      return PlaneswalkerNicknamePlateR;
    case ColorType.Green:
      return PlaneswalkerNicknamePlateG;
    case ColorType.Colorless:
      return PlaneswalkerNicknamePlateA;
    default:
      return PlaneswalkerNicknamePlateM;
  }
};

// Token frame parts, keyed by combo variant. Like the extended / borderless
// pinlines, only the two-color combinations exist; non-combo keys map to ''
// because single-color (and colorless / 3+ color) tokens render the whole
// token frame instead of carving a part out of it.
const TOKEN_PINLINES: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: TokenWhiteBluePinline,
  ub: TokenBlueBlackPinline,
  br: TokenBlackRedPinline,
  rg: TokenRedGreenPinline,
  gw: TokenGreenWhitePinline,
  wb: TokenWhiteBlackPinline,
  ur: TokenBlueRedPinline,
  bg: TokenBlackGreenPinline,
  rw: TokenRedWhitePinline,
  gu: TokenGreenBluePinline,
};

const TOKEN_RULES_PARTS: Record<PartVariant, string> = {
  '': '',
  w: '',
  u: '',
  b: '',
  r: '',
  g: '',
  m: '',
  wu: TokenWhiteBlueRules,
  ub: TokenBlueBlackRules,
  br: TokenBlackRedRules,
  rg: TokenRedGreenRules,
  gw: TokenGreenWhiteRules,
  wb: TokenWhiteBlackRules,
  ur: TokenBlueRedRules,
  bg: TokenBlackGreenRules,
  rw: TokenRedWhiteRules,
  gu: TokenGreenBlueRules,
};

// Tokens only ever carry a part for the two-color combinations; every other
// color count renders the whole token frame instead.
const getTokenPartVariant = (colors: ColorType[]): PartVariant =>
  colors.length === 2 ? getTwoColorVariant(colors) : '';

export const getTitlePart = (colors: ColorType[], isArtifact: boolean, isToken = false) =>
  isToken ? '' : TITLE_PARTS[getTitleTypeVariant(colors, isArtifact)];

export const getTypePart = (colors: ColorType[], isArtifact: boolean, isToken = false) =>
  isToken ? '' : TYPE_PARTS[getTitleTypeVariant(colors, isArtifact)];

export const getRulesPart = (colors: ColorType[], isArtifact: boolean, isToken = false) =>
  isToken
    ? TOKEN_RULES_PARTS[getTokenPartVariant(colors)]
    : RULES_PARTS[getRulesVariant(colors, isArtifact)];

// Lands only get frame parts when their card-text color identity has exactly
// two colors: the land ('l') title/type parts plus the two-color text part.
// Single-color, 3+ color, and colorless lands get no parts.
export const getLandTitlePart = (colors: ColorType[]) => (colors.length === 2 ? LandTitle : '');

export const getLandTypePart = (colors: ColorType[]) => (colors.length === 2 ? LandType : '');

// Token lands are colorless, so their type part is the single 'l' part carved
// from the token land frame itself (no color-combination variants exist).
export const getTokenLandTypePart = () => TokenLandType;

export const getLandRulesPart = (colors: ColorType[]) =>
  colors.length === 2 ? RULES_PARTS[getTwoColorVariant(colors)] : '';

export const getLandOverlay = () => LandOverlay;

export const getBasicLandSymbols = (landType: BasicLandType) => {
  switch (landType) {
    case BasicLandType.Plains:
      return SymbolLandWhite;
    case BasicLandType.Island:
      return SymbolLandBlue;
    case BasicLandType.Swamp:
      return SymbolLandBlack;
    case BasicLandType.Mountain:
      return SymbolLandRed;
    case BasicLandType.Forest:
      return SymbolLandGreen;
    default:
      return SymbolLandColorless;
  }
};

export const getLandMainframe = (
  color: ColorType,
  artStyle: BasicLandArtStyles | CardArtStyles | undefined,
): ImageResData | string => {
  switch (color) {
    case ColorType.White:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandWhiteMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandWhiteMainframe;
      return { highRes: LandWhiteMainframe, lowRes: LandWhiteMainframeLowRes };
    case ColorType.Blue:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandBlueMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandBlueMainframe;
      return { highRes: LandBlueMainframe, lowRes: LandBlueMainframeLowRes };
    case ColorType.Black:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandBlackMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandBlackMainframe;
      return { highRes: LandBlackMainframe, lowRes: LandBlackMainframeLowRes };
    case ColorType.Red:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandRedMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandRedMainframe;
      return { highRes: LandRedMainframe, lowRes: LandRedMainframeLowRes };
    case ColorType.Green:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandGreenMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandGreenMainframe;
      return { highRes: LandGreenMainframe, lowRes: LandGreenMainframeLowRes };
    case ColorType.Gold:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandGoldMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandGoldMainframe;
      return { highRes: LandGoldMainframe, lowRes: LandGoldMainframeLowRes };
    default:
      if (artStyle === BasicLandArtStyles.Unstable) return UnstableBasicLandGoldMainframe;
      if (artStyle === BasicLandArtStyles.FullArt) return FullArtBasicLandGoldMainframe;
      return { highRes: LandColorlessMainframe, lowRes: LandColorlessMainframeLowRes };
  }
};

export const getRarityIcon = (rarity: RarityType) => {
  if (rarity === RarityType.MythicRare) return MythicRareIcon;
  if (rarity === RarityType.Rare) return RareIcon;
  if (rarity === RarityType.Uncommon) return UncommonIcon;
  return CommonIcon;
};
